all: 
	pyuic5 HDF5VideoPlayer.ui -o ../HDF5VideoPlayer_ui.py
	pyuic5 TrackerViewerAux.ui -o ../TrackerViewerAux_ui.py
	pyuic5 MWTrackerViewer.ui -o ../MWTrackerViewer_ui.py
	pyuic5 SWTrackerViewer.ui -o ../SWTrackerViewer_ui.py
	pyuic5 GetMaskParams.ui -o ../GetMaskParams_ui.py
