# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GetMaskParams.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_GetMaskParams(object):
    def setupUi(self, GetMaskParams):
        GetMaskParams.setObjectName("GetMaskParams")
        GetMaskParams.resize(1038, 862)
        self.centralWidget = QtWidgets.QWidget(GetMaskParams)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_mask = QtWidgets.QWidget()
        self.tab_mask.setObjectName("tab_mask")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_mask)
        self.gridLayout_6.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_6.setSpacing(6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_min_area_2 = QtWidgets.QLabel(self.tab_mask)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_min_area_2.sizePolicy().hasHeightForWidth())
        self.label_min_area_2.setSizePolicy(sizePolicy)
        self.label_min_area_2.setObjectName("label_min_area_2")
        self.gridLayout_5.addWidget(self.label_min_area_2, 3, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 8, 1, 1, 2)
        self.p_microns_per_pixel = QtWidgets.QDoubleSpinBox(self.tab_mask)
        self.p_microns_per_pixel.setFrame(True)
        self.p_microns_per_pixel.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.p_microns_per_pixel.setAccelerated(False)
        self.p_microns_per_pixel.setKeyboardTracking(True)
        self.p_microns_per_pixel.setObjectName("p_microns_per_pixel")
        self.gridLayout_5.addWidget(self.p_microns_per_pixel, 6, 1, 1, 1)
        self.label_max_aea_2 = QtWidgets.QLabel(self.tab_mask)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_max_aea_2.sizePolicy().hasHeightForWidth())
        self.label_max_aea_2.setSizePolicy(sizePolicy)
        self.label_max_aea_2.setObjectName("label_max_aea_2")
        self.gridLayout_5.addWidget(self.label_max_aea_2, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 2, 1, 1, 2)
        self.p_analysis_type = QtWidgets.QComboBox(self.tab_mask)
        self.p_analysis_type.setObjectName("p_analysis_type")
        self.gridLayout_5.addWidget(self.p_analysis_type, 1, 1, 1, 2)
        self.label_min_area_3 = QtWidgets.QLabel(self.tab_mask)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_min_area_3.sizePolicy().hasHeightForWidth())
        self.label_min_area_3.setSizePolicy(sizePolicy)
        self.label_min_area_3.setObjectName("label_min_area_3")
        self.gridLayout_5.addWidget(self.label_min_area_3, 5, 1, 1, 1)
        self.p_expected_fps = QtWidgets.QDoubleSpinBox(self.tab_mask)
        self.p_expected_fps.setEnabled(True)
        self.p_expected_fps.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.p_expected_fps.setObjectName("p_expected_fps")
        self.gridLayout_5.addWidget(self.p_expected_fps, 4, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 2, 0, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout.setContentsMargins(11, 11, 11, 11)
        self.formLayout.setSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.p_compression_buff = QtWidgets.QSpinBox(self.tab_mask)
        self.p_compression_buff.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.p_compression_buff.setMinimum(1)
        self.p_compression_buff.setMaximum(1000)
        self.p_compression_buff.setProperty("value", 25)
        self.p_compression_buff.setObjectName("p_compression_buff")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.p_compression_buff)
        self.label_5 = QtWidgets.QLabel(self.tab_mask)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_5)
        self.p_keep_border_data = QtWidgets.QCheckBox(self.tab_mask)
        self.p_keep_border_data.setObjectName("p_keep_border_data")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.p_keep_border_data)
        self.p_is_light_background = QtWidgets.QCheckBox(self.tab_mask)
        self.p_is_light_background.setChecked(True)
        self.p_is_light_background.setObjectName("p_is_light_background")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.p_is_light_background)
        self.gridLayout_6.addLayout(self.formLayout, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_thresh_C = QtWidgets.QLabel(self.tab_mask)
        self.label_thresh_C.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_thresh_C.setObjectName("label_thresh_C")
        self.gridLayout_3.addWidget(self.label_thresh_C, 4, 2, 1, 1)
        self.horizontalSlider_mask_min_area = QtWidgets.QSlider(self.tab_mask)
        self.horizontalSlider_mask_min_area.setMaximum(10000)
        self.horizontalSlider_mask_min_area.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_mask_min_area.setObjectName("horizontalSlider_mask_min_area")
        self.gridLayout_3.addWidget(self.horizontalSlider_mask_min_area, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab_mask)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 8, 1, 1, 1)
        self.label_max_aea = QtWidgets.QLabel(self.tab_mask)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_max_aea.sizePolicy().hasHeightForWidth())
        self.label_max_aea.setSizePolicy(sizePolicy)
        self.label_max_aea.setObjectName("label_max_aea")
        self.gridLayout_3.addWidget(self.label_max_aea, 0, 2, 1, 1)
        self.horizontalSlider_thresh_C = QtWidgets.QSlider(self.tab_mask)
        self.horizontalSlider_thresh_C.setMaximum(100)
        self.horizontalSlider_thresh_C.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_thresh_C.setObjectName("horizontalSlider_thresh_C")
        self.gridLayout_3.addWidget(self.horizontalSlider_thresh_C, 5, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 3, 1, 1, 2)
        self.horizontalSlider_mask_max_area = QtWidgets.QSlider(self.tab_mask)
        self.horizontalSlider_mask_max_area.setMinimum(0)
        self.horizontalSlider_mask_max_area.setMaximum(100000)
        self.horizontalSlider_mask_max_area.setSingleStep(100)
        self.horizontalSlider_mask_max_area.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_mask_max_area.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.horizontalSlider_mask_max_area.setObjectName("horizontalSlider_mask_max_area")
        self.gridLayout_3.addWidget(self.horizontalSlider_mask_max_area, 1, 2, 1, 1)
        self.p_thresh_block_size = QtWidgets.QSpinBox(self.tab_mask)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p_thresh_block_size.sizePolicy().hasHeightForWidth())
        self.p_thresh_block_size.setSizePolicy(sizePolicy)
        self.p_thresh_block_size.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.p_thresh_block_size.setMinimum(5)
        self.p_thresh_block_size.setMaximum(1000000)
        self.p_thresh_block_size.setProperty("value", 61)
        self.p_thresh_block_size.setObjectName("p_thresh_block_size")
        self.gridLayout_3.addWidget(self.p_thresh_block_size, 6, 1, 1, 1)
        self.p_thresh_C = QtWidgets.QSpinBox(self.tab_mask)
        self.p_thresh_C.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.p_thresh_C.setMinimum(-100)
        self.p_thresh_C.setMaximum(100)
        self.p_thresh_C.setProperty("value", 15)
        self.p_thresh_C.setObjectName("p_thresh_C")
        self.gridLayout_3.addWidget(self.p_thresh_C, 6, 2, 1, 1)
        self.label_min_area = QtWidgets.QLabel(self.tab_mask)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_min_area.sizePolicy().hasHeightForWidth())
        self.label_min_area.setSizePolicy(sizePolicy)
        self.label_min_area.setObjectName("label_min_area")
        self.gridLayout_3.addWidget(self.label_min_area, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 7, 1, 1, 2)
        self.label_block_size = QtWidgets.QLabel(self.tab_mask)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_block_size.sizePolicy().hasHeightForWidth())
        self.label_block_size.setSizePolicy(sizePolicy)
        self.label_block_size.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_block_size.setObjectName("label_block_size")
        self.gridLayout_3.addWidget(self.label_block_size, 4, 1, 1, 1)
        self.p_dilation_size = QtWidgets.QSpinBox(self.tab_mask)
        self.p_dilation_size.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.p_dilation_size.setMinimum(1)
        self.p_dilation_size.setMaximum(999)
        self.p_dilation_size.setProperty("value", 9)
        self.p_dilation_size.setObjectName("p_dilation_size")
        self.gridLayout_3.addWidget(self.p_dilation_size, 10, 1, 1, 1)
        self.horizontalSlider_dilation_size = QtWidgets.QSlider(self.tab_mask)
        self.horizontalSlider_dilation_size.setMinimum(1)
        self.horizontalSlider_dilation_size.setMaximum(100)
        self.horizontalSlider_dilation_size.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_dilation_size.setObjectName("horizontalSlider_dilation_size")
        self.gridLayout_3.addWidget(self.horizontalSlider_dilation_size, 9, 1, 1, 1)
        self.p_mask_max_area = QtWidgets.QSpinBox(self.tab_mask)
        self.p_mask_max_area.setFrame(True)
        self.p_mask_max_area.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.p_mask_max_area.setAccelerated(False)
        self.p_mask_max_area.setKeyboardTracking(True)
        self.p_mask_max_area.setMinimum(10)
        self.p_mask_max_area.setMaximum(100000000)
        self.p_mask_max_area.setProperty("value", 5000)
        self.p_mask_max_area.setProperty("showGroupSeparator", False)
        self.p_mask_max_area.setObjectName("p_mask_max_area")
        self.gridLayout_3.addWidget(self.p_mask_max_area, 2, 2, 1, 1)
        self.p_mask_min_area = QtWidgets.QSpinBox(self.tab_mask)
        self.p_mask_min_area.setEnabled(True)
        self.p_mask_min_area.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.p_mask_min_area.setMaximum(100000000)
        self.p_mask_min_area.setProperty("value", 100)
        self.p_mask_min_area.setObjectName("p_mask_min_area")
        self.gridLayout_3.addWidget(self.p_mask_min_area, 2, 1, 1, 1)
        self.horizontalSlider_thresh_block_size = QtWidgets.QSlider(self.tab_mask)
        self.horizontalSlider_thresh_block_size.setMaximum(500)
        self.horizontalSlider_thresh_block_size.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_thresh_block_size.setObjectName("horizontalSlider_thresh_block_size")
        self.gridLayout_3.addWidget(self.horizontalSlider_thresh_block_size, 5, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.gridLayout_6.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_mask, "")
        self.tab_bgnd = QtWidgets.QWidget()
        self.tab_bgnd.setObjectName("tab_bgnd")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_bgnd)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.checkBox_is_bgnd_subtraction = QtWidgets.QCheckBox(self.tab_bgnd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_is_bgnd_subtraction.sizePolicy().hasHeightForWidth())
        self.checkBox_is_bgnd_subtraction.setSizePolicy(sizePolicy)
        self.checkBox_is_bgnd_subtraction.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_is_bgnd_subtraction.setObjectName("checkBox_is_bgnd_subtraction")
        self.verticalLayout_3.addWidget(self.checkBox_is_bgnd_subtraction)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label = QtWidgets.QLabel(self.tab_bgnd)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.p_mask_bgnd_buff_size = QtWidgets.QSpinBox(self.tab_bgnd)
        self.p_mask_bgnd_buff_size.setMinimum(1)
        self.p_mask_bgnd_buff_size.setMaximum(200)
        self.p_mask_bgnd_buff_size.setProperty("value", 25)
        self.p_mask_bgnd_buff_size.setObjectName("p_mask_bgnd_buff_size")
        self.gridLayout_4.addWidget(self.p_mask_bgnd_buff_size, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_bgnd)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 2, 0, 1, 1)
        self.p_mask_bgnd_frame_gap = QtWidgets.QSpinBox(self.tab_bgnd)
        self.p_mask_bgnd_frame_gap.setMinimum(1)
        self.p_mask_bgnd_frame_gap.setMaximum(1000000)
        self.p_mask_bgnd_frame_gap.setProperty("value", 250)
        self.p_mask_bgnd_frame_gap.setObjectName("p_mask_bgnd_frame_gap")
        self.gridLayout_4.addWidget(self.p_mask_bgnd_frame_gap, 3, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_4)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.tabWidget.addTab(self.tab_bgnd, "")
        self.verticalLayout_5.addWidget(self.tabWidget)
        self.pushButton_moreParams = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_moreParams.setObjectName("pushButton_moreParams")
        self.verticalLayout_5.addWidget(self.pushButton_moreParams)
        self.pushButton_saveParam = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_saveParam.sizePolicy().hasHeightForWidth())
        self.pushButton_saveParam.setSizePolicy(sizePolicy)
        self.pushButton_saveParam.setObjectName("pushButton_saveParam")
        self.verticalLayout_5.addWidget(self.pushButton_saveParam)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.graphicsView_full = QtWidgets.QGraphicsView(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView_full.sizePolicy().hasHeightForWidth())
        self.graphicsView_full.setSizePolicy(sizePolicy)
        self.graphicsView_full.setDragMode(QtWidgets.QGraphicsView.ScrollHandDrag)
        self.graphicsView_full.setTransformationAnchor(QtWidgets.QGraphicsView.AnchorUnderMouse)
        self.graphicsView_full.setResizeAnchor(QtWidgets.QGraphicsView.AnchorViewCenter)
        self.graphicsView_full.setObjectName("graphicsView_full")
        self.horizontalLayout_2.addWidget(self.graphicsView_full)
        self.graphicsView_mask = QtWidgets.QGraphicsView(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView_mask.sizePolicy().hasHeightForWidth())
        self.graphicsView_mask.setSizePolicy(sizePolicy)
        self.graphicsView_mask.setDragMode(QtWidgets.QGraphicsView.ScrollHandDrag)
        self.graphicsView_mask.setTransformationAnchor(QtWidgets.QGraphicsView.AnchorUnderMouse)
        self.graphicsView_mask.setResizeAnchor(QtWidgets.QGraphicsView.AnchorViewCenter)
        self.graphicsView_mask.setObjectName("graphicsView_mask")
        self.horizontalLayout_2.addWidget(self.graphicsView_mask)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.widget = QtWidgets.QWidget(self.centralWidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_paramFile = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_paramFile.setObjectName("lineEdit_paramFile")
        self.gridLayout.addWidget(self.lineEdit_paramFile, 1, 1, 1, 1)
        self.lineEdit_video = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_video.setObjectName("lineEdit_video")
        self.gridLayout.addWidget(self.lineEdit_video, 0, 1, 1, 1)
        self.pushButton_video = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_video.sizePolicy().hasHeightForWidth())
        self.pushButton_video.setSizePolicy(sizePolicy)
        self.pushButton_video.setObjectName("pushButton_video")
        self.gridLayout.addWidget(self.pushButton_video, 0, 0, 1, 1)
        self.pushButton_paramFile = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_paramFile.sizePolicy().hasHeightForWidth())
        self.pushButton_paramFile.setSizePolicy(sizePolicy)
        self.pushButton_paramFile.setObjectName("pushButton_paramFile")
        self.gridLayout.addWidget(self.pushButton_paramFile, 1, 0, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.spinBox_frame_number = QtWidgets.QSpinBox(self.widget)
        self.spinBox_frame_number.setEnabled(False)
        self.spinBox_frame_number.setAutoFillBackground(False)
        self.spinBox_frame_number.setWrapping(False)
        self.spinBox_frame_number.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_frame_number.setReadOnly(True)
        self.spinBox_frame_number.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_frame_number.setAccelerated(False)
        self.spinBox_frame_number.setMaximum(100000000)
        self.spinBox_frame_number.setProperty("showGroupSeparator", False)
        self.spinBox_frame_number.setObjectName("spinBox_frame_number")
        self.gridLayout_2.addWidget(self.spinBox_frame_number, 1, 1, 1, 1)
        self.pushButton_next = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_next.sizePolicy().hasHeightForWidth())
        self.pushButton_next.setSizePolicy(sizePolicy)
        self.pushButton_next.setObjectName("pushButton_next")
        self.gridLayout_2.addWidget(self.pushButton_next, 2, 1, 1, 1)
        self.pushButton_play = QtWidgets.QPushButton(self.widget)
        self.pushButton_play.setObjectName("pushButton_play")
        self.gridLayout_2.addWidget(self.pushButton_play, 0, 1, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.horizontalLayout_4.addWidget(self.widget)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5.addLayout(self.verticalLayout_7)
        self.horizontalLayout_5.setStretch(1, 8)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        GetMaskParams.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(GetMaskParams)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1038, 22))
        self.menuBar.setObjectName("menuBar")
        GetMaskParams.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(GetMaskParams)
        self.mainToolBar.setObjectName("mainToolBar")
        GetMaskParams.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(GetMaskParams)
        self.statusBar.setObjectName("statusBar")
        GetMaskParams.setStatusBar(self.statusBar)

        self.retranslateUi(GetMaskParams)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(GetMaskParams)

    def retranslateUi(self, GetMaskParams):
        _translate = QtCore.QCoreApplication.translate
        GetMaskParams.setWindowTitle(_translate("GetMaskParams", "GetMaskParams"))
        self.label_min_area_2.setText(_translate("GetMaskParams", "Frames per Second"))
        self.label_max_aea_2.setText(_translate("GetMaskParams", "Analysis Type"))
        self.label_min_area_3.setText(_translate("GetMaskParams", "Microns per Pixel"))
        self.label_5.setText(_translate("GetMaskParams", "Frames to Average"))
        self.p_keep_border_data.setText(_translate("GetMaskParams", "Keep Border Data?"))
        self.p_is_light_background.setText(_translate("GetMaskParams", "Is Light Background?"))
        self.label_thresh_C.setText(_translate("GetMaskParams", "Threshold"))
        self.label_6.setText(_translate("GetMaskParams", "Dilation"))
        self.label_max_aea.setText(_translate("GetMaskParams", "Max Area"))
        self.label_min_area.setText(_translate("GetMaskParams", "Min Area"))
        self.label_block_size.setText(_translate("GetMaskParams", "Block Size"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_mask), _translate("GetMaskParams", "Mask"))
        self.checkBox_is_bgnd_subtraction.setText(_translate("GetMaskParams", "Subtract Background"))
        self.label.setText(_translate("GetMaskParams", "Background buffer size"))
        self.label_2.setText(_translate("GetMaskParams", "Gap between frames"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_bgnd), _translate("GetMaskParams", "Background"))
        self.pushButton_moreParams.setText(_translate("GetMaskParams", "Edit More Parameters"))
        self.pushButton_saveParam.setText(_translate("GetMaskParams", "Save Parameters"))
        self.pushButton_video.setText(_translate("GetMaskParams", "Video File"))
        self.pushButton_paramFile.setText(_translate("GetMaskParams", "Parameters File"))
        self.pushButton_next.setText(_translate("GetMaskParams", "Next Chunk"))
        self.pushButton_play.setText(_translate("GetMaskParams", "Play"))

