# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MWTrackerViewer.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MWTrackerViewer(object):
    def setupUi(self, MWTrackerViewer):
        MWTrackerViewer.setObjectName("MWTrackerViewer")
        MWTrackerViewer.resize(1081, 845)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MWTrackerViewer.sizePolicy().hasHeightForWidth())
        MWTrackerViewer.setSizePolicy(sizePolicy)
        MWTrackerViewer.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralWidget = QtWidgets.QWidget(MWTrackerViewer)
        self.centralWidget.setEnabled(True)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_video = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_video.setText("")
        self.lineEdit_video.setObjectName("lineEdit_video")
        self.gridLayout.addWidget(self.lineEdit_video, 4, 5, 1, 8)
        self.pushButton_h5groups = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_h5groups.setObjectName("pushButton_h5groups")
        self.gridLayout.addWidget(self.pushButton_h5groups, 6, 0, 1, 2)
        self.spinBox_step = QtWidgets.QSpinBox(self.centralWidget)
        self.spinBox_step.setMaximum(100000)
        self.spinBox_step.setProperty("value", 1)
        self.spinBox_step.setObjectName("spinBox_step")
        self.gridLayout.addWidget(self.spinBox_step, 2, 1, 1, 1)
        self.comboBox_h5path = QtWidgets.QComboBox(self.centralWidget)
        self.comboBox_h5path.setEditable(True)
        self.comboBox_h5path.setObjectName("comboBox_h5path")
        self.comboBox_h5path.addItem("")
        self.comboBox_h5path.addItem("")
        self.gridLayout.addWidget(self.comboBox_h5path, 6, 5, 1, 8)
        self.playButton = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playButton.sizePolicy().hasHeightForWidth())
        self.playButton.setSizePolicy(sizePolicy)
        self.playButton.setCheckable(False)
        self.playButton.setObjectName("playButton")
        self.gridLayout.addWidget(self.playButton, 0, 12, 1, 1)
        self.label_step = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_step.setFont(font)
        self.label_step.setAlignment(QtCore.Qt.AlignCenter)
        self.label_step.setObjectName("label_step")
        self.gridLayout.addWidget(self.label_step, 2, 0, 1, 1)
        self.pushButton_skel = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_skel.sizePolicy().hasHeightForWidth())
        self.pushButton_skel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_skel.setFont(font)
        self.pushButton_skel.setObjectName("pushButton_skel")
        self.gridLayout.addWidget(self.pushButton_skel, 5, 0, 1, 2)
        self.imageSlider = QtWidgets.QSlider(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageSlider.sizePolicy().hasHeightForWidth())
        self.imageSlider.setSizePolicy(sizePolicy)
        self.imageSlider.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.imageSlider.setMouseTracking(True)
        self.imageSlider.setAutoFillBackground(False)
        self.imageSlider.setMaximum(100)
        self.imageSlider.setOrientation(QtCore.Qt.Horizontal)
        self.imageSlider.setInvertedAppearance(False)
        self.imageSlider.setInvertedControls(False)
        self.imageSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.imageSlider.setObjectName("imageSlider")
        self.gridLayout.addWidget(self.imageSlider, 0, 5, 1, 7)
        self.pushButton_video = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_video.sizePolicy().hasHeightForWidth())
        self.pushButton_video.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_video.setFont(font)
        self.pushButton_video.setObjectName("pushButton_video")
        self.gridLayout.addWidget(self.pushButton_video, 4, 0, 1, 2)
        self.lineEdit_skel = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_skel.setObjectName("lineEdit_skel")
        self.gridLayout.addWidget(self.lineEdit_skel, 5, 5, 1, 8)
        self.label_frame = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_frame.setFont(font)
        self.label_frame.setAlignment(QtCore.Qt.AlignCenter)
        self.label_frame.setObjectName("label_frame")
        self.gridLayout.addWidget(self.label_frame, 0, 0, 1, 1)
        self.doubleSpinBox_fps = QtWidgets.QDoubleSpinBox(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_fps.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_fps.setSizePolicy(sizePolicy)
        self.doubleSpinBox_fps.setMaximum(100.0)
        self.doubleSpinBox_fps.setProperty("value", 25.0)
        self.doubleSpinBox_fps.setObjectName("doubleSpinBox_fps")
        self.gridLayout.addWidget(self.doubleSpinBox_fps, 3, 1, 1, 1)
        self.spinBox_frame = QtWidgets.QSpinBox(self.centralWidget)
        self.spinBox_frame.setObjectName("spinBox_frame")
        self.gridLayout.addWidget(self.spinBox_frame, 0, 1, 1, 1)
        self.label_fps = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_fps.sizePolicy().hasHeightForWidth())
        self.label_fps.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_fps.setFont(font)
        self.label_fps.setAlignment(QtCore.Qt.AlignCenter)
        self.label_fps.setObjectName("label_fps")
        self.gridLayout.addWidget(self.label_fps, 3, 0, 1, 1)
        self.pushButton_save = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_save.sizePolicy().hasHeightForWidth())
        self.pushButton_save.setSizePolicy(sizePolicy)
        self.pushButton_save.setObjectName("pushButton_save")
        self.gridLayout.addWidget(self.pushButton_save, 2, 12, 2, 1)
        self.feature_column = QtWidgets.QComboBox(self.centralWidget)
        self.feature_column.setObjectName("feature_column")
        self.gridLayout.addWidget(self.feature_column, 2, 6, 1, 1)
        self.pushButton_WS = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_WS.sizePolicy().hasHeightForWidth())
        self.pushButton_WS.setSizePolicy(sizePolicy)
        self.pushButton_WS.setObjectName("pushButton_WS")
        self.gridLayout.addWidget(self.pushButton_WS, 2, 11, 1, 1)
        self.is_color_features = QtWidgets.QCheckBox(self.centralWidget)
        self.is_color_features.setObjectName("is_color_features")
        self.gridLayout.addWidget(self.is_color_features, 2, 5, 1, 1)
        self.pushButton_U = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_U.sizePolicy().hasHeightForWidth())
        self.pushButton_U.setSizePolicy(sizePolicy)
        self.pushButton_U.setObjectName("pushButton_U")
        self.gridLayout.addWidget(self.pushButton_U, 2, 10, 1, 1)
        self.feat_min_value = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.feat_min_value.setObjectName("feat_min_value")
        self.gridLayout.addWidget(self.feat_min_value, 3, 5, 1, 1)
        self.feat_max_value = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.feat_max_value.setObjectName("feat_max_value")
        self.gridLayout.addWidget(self.feat_max_value, 3, 6, 1, 1)
        self.pushButton_W = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_W.setObjectName("pushButton_W")
        self.gridLayout.addWidget(self.pushButton_W, 3, 11, 1, 1)
        self.pushButton_B = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_B.setObjectName("pushButton_B")
        self.gridLayout.addWidget(self.pushButton_B, 3, 10, 1, 1)
        self.pushButton_plot = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_plot.setObjectName("pushButton_plot")
        self.gridLayout.addWidget(self.pushButton_plot, 2, 7, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_ROI2_RW = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ROI2_RW.sizePolicy().hasHeightForWidth())
        self.pushButton_ROI2_RW.setSizePolicy(sizePolicy)
        self.pushButton_ROI2_RW.setObjectName("pushButton_ROI2_RW")
        self.gridLayout_3.addWidget(self.pushButton_ROI2_RW, 2, 15, 1, 1)
        self.pushButton_ROI2_FF = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ROI2_FF.sizePolicy().hasHeightForWidth())
        self.pushButton_ROI2_FF.setSizePolicy(sizePolicy)
        self.pushButton_ROI2_FF.setObjectName("pushButton_ROI2_FF")
        self.gridLayout_3.addWidget(self.pushButton_ROI2_FF, 2, 16, 1, 1)
        self.mainGraphicsView = QtWidgets.QGraphicsView(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainGraphicsView.sizePolicy().hasHeightForWidth())
        self.mainGraphicsView.setSizePolicy(sizePolicy)
        self.mainGraphicsView.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.mainGraphicsView.setFrameShape(QtWidgets.QFrame.Box)
        self.mainGraphicsView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.mainGraphicsView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.mainGraphicsView.setDragMode(QtWidgets.QGraphicsView.ScrollHandDrag)
        self.mainGraphicsView.setTransformationAnchor(QtWidgets.QGraphicsView.AnchorUnderMouse)
        self.mainGraphicsView.setResizeAnchor(QtWidgets.QGraphicsView.AnchorUnderMouse)
        self.mainGraphicsView.setObjectName("mainGraphicsView")
        self.gridLayout_3.addWidget(self.mainGraphicsView, 0, 0, 4, 8)
        self.comboBox_showLabels = QtWidgets.QComboBox(self.centralWidget)
        self.comboBox_showLabels.setObjectName("comboBox_showLabels")
        self.comboBox_showLabels.addItem("")
        self.comboBox_showLabels.addItem("")
        self.comboBox_showLabels.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_showLabels, 4, 1, 1, 1)
        self.radioButton_ROI1 = QtWidgets.QRadioButton(self.centralWidget)
        self.radioButton_ROI1.setText("")
        self.radioButton_ROI1.setChecked(True)
        self.radioButton_ROI1.setObjectName("radioButton_ROI1")
        self.gridLayout_3.addWidget(self.radioButton_ROI1, 1, 11, 1, 1)
        self.pushButton_ROI1_RW = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ROI1_RW.sizePolicy().hasHeightForWidth())
        self.pushButton_ROI1_RW.setSizePolicy(sizePolicy)
        self.pushButton_ROI1_RW.setObjectName("pushButton_ROI1_RW")
        self.gridLayout_3.addWidget(self.pushButton_ROI1_RW, 1, 15, 1, 1)
        self.radioButton_ROI2 = QtWidgets.QRadioButton(self.centralWidget)
        self.radioButton_ROI2.setText("")
        self.radioButton_ROI2.setObjectName("radioButton_ROI2")
        self.gridLayout_3.addWidget(self.radioButton_ROI2, 2, 11, 1, 1)
        self.comboBox_labelType = QtWidgets.QComboBox(self.centralWidget)
        self.comboBox_labelType.setObjectName("comboBox_labelType")
        self.comboBox_labelType.addItem("")
        self.comboBox_labelType.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_labelType, 4, 3, 1, 1)
        self.wormCanvas1 = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wormCanvas1.sizePolicy().hasHeightForWidth())
        self.wormCanvas1.setSizePolicy(sizePolicy)
        self.wormCanvas1.setFrameShape(QtWidgets.QFrame.Box)
        self.wormCanvas1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.wormCanvas1.setText("")
        self.wormCanvas1.setObjectName("wormCanvas1")
        self.gridLayout_3.addWidget(self.wormCanvas1, 0, 11, 1, 7)
        self.wormCanvas2 = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wormCanvas2.sizePolicy().hasHeightForWidth())
        self.wormCanvas2.setSizePolicy(sizePolicy)
        self.wormCanvas2.setFrameShape(QtWidgets.QFrame.Box)
        self.wormCanvas2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.wormCanvas2.setText("")
        self.wormCanvas2.setObjectName("wormCanvas2")
        self.gridLayout_3.addWidget(self.wormCanvas2, 3, 11, 1, 7)
        self.pushButton_ROI1_FF = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ROI1_FF.sizePolicy().hasHeightForWidth())
        self.pushButton_ROI1_FF.setSizePolicy(sizePolicy)
        self.pushButton_ROI1_FF.setObjectName("pushButton_ROI1_FF")
        self.gridLayout_3.addWidget(self.pushButton_ROI1_FF, 1, 16, 1, 1)
        self.comboBox_drawType = QtWidgets.QComboBox(self.centralWidget)
        self.comboBox_drawType.setObjectName("comboBox_drawType")
        self.comboBox_drawType.addItem("")
        self.comboBox_drawType.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_drawType, 4, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(600, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 4, 5, 1, 1)
        self.comboBox_ROI1 = QtWidgets.QComboBox(self.centralWidget)
        self.comboBox_ROI1.setEditable(True)
        self.comboBox_ROI1.setObjectName("comboBox_ROI1")
        self.gridLayout_3.addWidget(self.comboBox_ROI1, 1, 17, 1, 1)
        self.comboBox_ROI2 = QtWidgets.QComboBox(self.centralWidget)
        self.comboBox_ROI2.setEditable(True)
        self.comboBox_ROI2.setObjectName("comboBox_ROI2")
        self.gridLayout_3.addWidget(self.comboBox_ROI2, 2, 17, 1, 1)
        self.pushButton_join = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_join.setObjectName("pushButton_join")
        self.gridLayout_3.addWidget(self.pushButton_join, 4, 17, 1, 1)
        self.checkBox_ROI1 = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_ROI1.setChecked(True)
        self.checkBox_ROI1.setObjectName("checkBox_ROI1")
        self.gridLayout_3.addWidget(self.checkBox_ROI1, 1, 12, 1, 3)
        self.checkBox_ROI2 = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_ROI2.setChecked(True)
        self.checkBox_ROI2.setObjectName("checkBox_ROI2")
        self.gridLayout_3.addWidget(self.checkBox_ROI2, 2, 12, 1, 3)
        self.intensity_label = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.intensity_label.sizePolicy().hasHeightForWidth())
        self.intensity_label.setSizePolicy(sizePolicy)
        self.intensity_label.setStyleSheet("QLabel {background-color: #000000;}")
        self.intensity_label.setText("")
        self.intensity_label.setObjectName("intensity_label")
        self.gridLayout_3.addWidget(self.intensity_label, 4, 11, 1, 4)
        self.pushButton_split = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_split.sizePolicy().hasHeightForWidth())
        self.pushButton_split.setSizePolicy(sizePolicy)
        self.pushButton_split.setObjectName("pushButton_split")
        self.gridLayout_3.addWidget(self.pushButton_split, 4, 15, 1, 2)
        self.checkBox_showFood = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_showFood.setObjectName("checkBox_showFood")
        self.gridLayout_3.addWidget(self.checkBox_showFood, 4, 6, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        MWTrackerViewer.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MWTrackerViewer)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1081, 22))
        self.menuBar.setObjectName("menuBar")
        MWTrackerViewer.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MWTrackerViewer)
        self.mainToolBar.setObjectName("mainToolBar")
        MWTrackerViewer.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.toolBar = QtWidgets.QToolBar(MWTrackerViewer)
        self.toolBar.setObjectName("toolBar")
        MWTrackerViewer.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MWTrackerViewer)
        QtCore.QMetaObject.connectSlotsByName(MWTrackerViewer)

    def retranslateUi(self, MWTrackerViewer):
        _translate = QtCore.QCoreApplication.translate
        MWTrackerViewer.setWindowTitle(_translate("MWTrackerViewer", "MWTrackerViewer"))
        self.pushButton_h5groups.setText(_translate("MWTrackerViewer", "Update Groups"))
        self.comboBox_h5path.setItemText(0, _translate("MWTrackerViewer", "/mask"))
        self.comboBox_h5path.setItemText(1, _translate("MWTrackerViewer", "/full_data"))
        self.playButton.setText(_translate("MWTrackerViewer", "Play"))
        self.label_step.setText(_translate("MWTrackerViewer", "Step Size"))
        self.pushButton_skel.setText(_translate("MWTrackerViewer", "Select Skeletons File"))
        self.pushButton_video.setText(_translate("MWTrackerViewer", "Select Video File"))
        self.label_frame.setText(_translate("MWTrackerViewer", "Frame"))
        self.label_fps.setText(_translate("MWTrackerViewer", "FPS display"))
        self.pushButton_save.setText(_translate("MWTrackerViewer", "SAVE"))
        self.pushButton_WS.setText(_translate("MWTrackerViewer", "Worm Cluster"))
        self.is_color_features.setText(_translate("MWTrackerViewer", "Color Features"))
        self.pushButton_U.setText(_translate("MWTrackerViewer", "Undefined"))
        self.pushButton_W.setText(_translate("MWTrackerViewer", "Single Worms"))
        self.pushButton_B.setText(_translate("MWTrackerViewer", "Bad"))
        self.pushButton_plot.setText(_translate("MWTrackerViewer", "PLOT"))
        self.pushButton_ROI2_RW.setText(_translate("MWTrackerViewer", "<<"))
        self.pushButton_ROI2_FF.setText(_translate("MWTrackerViewer", ">>"))
        self.comboBox_showLabels.setItemText(0, _translate("MWTrackerViewer", "hide labels"))
        self.comboBox_showLabels.setItemText(1, _translate("MWTrackerViewer", "all labels"))
        self.comboBox_showLabels.setItemText(2, _translate("MWTrackerViewer", "filtered labels"))
        self.pushButton_ROI1_RW.setText(_translate("MWTrackerViewer", "<<"))
        self.comboBox_labelType.setItemText(0, _translate("MWTrackerViewer", "manual index"))
        self.comboBox_labelType.setItemText(1, _translate("MWTrackerViewer", "auto index"))
        self.pushButton_ROI1_FF.setText(_translate("MWTrackerViewer", ">>"))
        self.comboBox_drawType.setItemText(0, _translate("MWTrackerViewer", "draw boxes"))
        self.comboBox_drawType.setItemText(1, _translate("MWTrackerViewer", "draw trajectories"))
        self.pushButton_join.setText(_translate("MWTrackerViewer", "Join Trajectory"))
        self.checkBox_ROI1.setText(_translate("MWTrackerViewer", "Skeleton"))
        self.checkBox_ROI2.setText(_translate("MWTrackerViewer", "Skeleton"))
        self.pushButton_split.setText(_translate("MWTrackerViewer", "Split Trajectory"))
        self.checkBox_showFood.setText(_translate("MWTrackerViewer", "Show Food Contour"))
        self.toolBar.setWindowTitle(_translate("MWTrackerViewer", "toolBar"))

