# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Summarizer.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Summarizer(object):
    def setupUi(self, Summarizer):
        Summarizer.setObjectName("Summarizer")
        Summarizer.resize(692, 323)
        self.centralwidget = QtWidgets.QWidget(Summarizer)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_rootdir = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_rootdir.sizePolicy().hasHeightForWidth())
        self.pushButton_rootdir.setSizePolicy(sizePolicy)
        self.pushButton_rootdir.setObjectName("pushButton_rootdir")
        self.gridLayout_2.addWidget(self.pushButton_rootdir, 0, 0, 1, 1)
        self.p_root_dir = QtWidgets.QLineEdit(self.centralwidget)
        self.p_root_dir.setObjectName("p_root_dir")
        self.gridLayout_2.addWidget(self.p_root_dir, 0, 1, 1, 2)
        self.p_feature_type = QtWidgets.QComboBox(self.centralwidget)
        self.p_feature_type.setObjectName("p_feature_type")
        self.gridLayout_2.addWidget(self.p_feature_type, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.p_is_manual_index = QtWidgets.QCheckBox(self.centralwidget)
        self.p_is_manual_index.setObjectName("p_is_manual_index")
        self.gridLayout_2.addWidget(self.p_is_manual_index, 1, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)
        self.p_summary_type = QtWidgets.QComboBox(self.centralwidget)
        self.p_summary_type.setObjectName("p_summary_type")
        self.gridLayout_2.addWidget(self.p_summary_type, 2, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.FoldArgs = QtWidgets.QWidget(self.centralwidget)
        self.FoldArgs.setObjectName("FoldArgs")
        self.gridLayout = QtWidgets.QGridLayout(self.FoldArgs)
        self.gridLayout.setObjectName("gridLayout")
        self.p_frac_worms_to_keep = QtWidgets.QDoubleSpinBox(self.FoldArgs)
        self.p_frac_worms_to_keep.setMaximum(1.0)
        self.p_frac_worms_to_keep.setSingleStep(0.01)
        self.p_frac_worms_to_keep.setObjectName("p_frac_worms_to_keep")
        self.gridLayout.addWidget(self.p_frac_worms_to_keep, 0, 1, 1, 1)
        self.p_n_folds = QtWidgets.QSpinBox(self.FoldArgs)
        self.p_n_folds.setObjectName("p_n_folds")
        self.gridLayout.addWidget(self.p_n_folds, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.FoldArgs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.FoldArgs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.FoldArgs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 2, 1, 1)
        self.p_time_sample_seconds = QtWidgets.QDoubleSpinBox(self.FoldArgs)
        self.p_time_sample_seconds.setMaximum(100000000000.0)
        self.p_time_sample_seconds.setObjectName("p_time_sample_seconds")
        self.gridLayout.addWidget(self.p_time_sample_seconds, 0, 2, 1, 1)
        self.verticalLayout_3.addWidget(self.FoldArgs)
        self.pushButton_start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start.setObjectName("pushButton_start")
        self.verticalLayout_3.addWidget(self.pushButton_start)
        Summarizer.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Summarizer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 692, 22))
        self.menubar.setObjectName("menubar")
        Summarizer.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Summarizer)
        self.statusbar.setObjectName("statusbar")
        Summarizer.setStatusBar(self.statusbar)

        self.retranslateUi(Summarizer)
        QtCore.QMetaObject.connectSlotsByName(Summarizer)

    def retranslateUi(self, Summarizer):
        _translate = QtCore.QCoreApplication.translate
        Summarizer.setWindowTitle(_translate("Summarizer", "MainWindow"))
        self.pushButton_rootdir.setText(_translate("Summarizer", "Root  Directory"))
        self.label_4.setText(_translate("Summarizer", "Features Type"))
        self.p_is_manual_index.setText(_translate("Summarizer", "Use manually \n"
"edited trajectories?"))
        self.label_5.setText(_translate("Summarizer", "Summary Type"))
        self.label_2.setText(_translate("Summarizer", "Fraction of trajectories\n"
" to sample"))
        self.label.setText(_translate("Summarizer", "Number of Folds"))
        self.label_3.setText(_translate("Summarizer", "Time (seconds)\n"
" to sample"))
        self.pushButton_start.setText(_translate("Summarizer", "START"))

