# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Summarizer.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Summarizer(object):
    def setupUi(self, Summarizer):
        Summarizer.setObjectName("Summarizer")
        Summarizer.resize(729, 906)
        self.centralwidget = QtWidgets.QWidget(Summarizer)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)
        self.p_feature_type = QtWidgets.QComboBox(self.centralwidget)
        self.p_feature_type.setObjectName("p_feature_type")
        self.gridLayout_2.addWidget(self.p_feature_type, 1, 1, 1, 1)
        self.p_root_dir = QtWidgets.QLineEdit(self.centralwidget)
        self.p_root_dir.setObjectName("p_root_dir")
        self.gridLayout_2.addWidget(self.p_root_dir, 0, 1, 1, 2)
        self.p_is_manual_index = QtWidgets.QCheckBox(self.centralwidget)
        self.p_is_manual_index.setObjectName("p_is_manual_index")
        self.gridLayout_2.addWidget(self.p_is_manual_index, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.pushButton_rootdir = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_rootdir.sizePolicy().hasHeightForWidth())
        self.pushButton_rootdir.setSizePolicy(sizePolicy)
        self.pushButton_rootdir.setObjectName("pushButton_rootdir")
        self.gridLayout_2.addWidget(self.pushButton_rootdir, 0, 0, 1, 1)
        self.p_summary_type = QtWidgets.QComboBox(self.centralwidget)
        self.p_summary_type.setObjectName("p_summary_type")
        self.gridLayout_2.addWidget(self.p_summary_type, 2, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.FoldArgs = QtWidgets.QWidget(self.centralwidget)
        self.FoldArgs.setObjectName("FoldArgs")
        self.gridLayout = QtWidgets.QGridLayout(self.FoldArgs)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.FoldArgs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.p_frac_worms_to_keep = QtWidgets.QDoubleSpinBox(self.FoldArgs)
        self.p_frac_worms_to_keep.setMaximum(1.0)
        self.p_frac_worms_to_keep.setSingleStep(0.01)
        self.p_frac_worms_to_keep.setObjectName("p_frac_worms_to_keep")
        self.gridLayout.addWidget(self.p_frac_worms_to_keep, 0, 1, 1, 1)
        self.p_n_folds = QtWidgets.QSpinBox(self.FoldArgs)
        self.p_n_folds.setObjectName("p_n_folds")
        self.gridLayout.addWidget(self.p_n_folds, 0, 0, 1, 1)
        self.p_time_sample_seconds = QtWidgets.QDoubleSpinBox(self.FoldArgs)
        self.p_time_sample_seconds.setMaximum(100000000000.0)
        self.p_time_sample_seconds.setObjectName("p_time_sample_seconds")
        self.gridLayout.addWidget(self.p_time_sample_seconds, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.FoldArgs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.FoldArgs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 2, 1, 1)
        self.verticalLayout_3.addWidget(self.FoldArgs)
        self.TimeWindows = QtWidgets.QWidget(self.centralwidget)
        self.TimeWindows.setObjectName("TimeWindows")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.TimeWindows)
        self.verticalLayout.setObjectName("verticalLayout")
        self.line = QtWidgets.QFrame(self.TimeWindows)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.label_6 = QtWidgets.QLabel(self.TimeWindows)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.p_time_windows = QtWidgets.QLineEdit(self.TimeWindows)
        self.p_time_windows.setObjectName("p_time_windows")
        self.gridLayout_5.addWidget(self.p_time_windows, 0, 1, 1, 1)
        self.p_time_units = QtWidgets.QComboBox(self.TimeWindows)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p_time_units.sizePolicy().hasHeightForWidth())
        self.p_time_units.setSizePolicy(sizePolicy)
        self.p_time_units.setObjectName("p_time_units")
        self.gridLayout_5.addWidget(self.p_time_units, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_5)
        self.verticalLayout_3.addWidget(self.TimeWindows)
        self.FeatureSelection = QtWidgets.QWidget(self.centralwidget)
        self.FeatureSelection.setObjectName("FeatureSelection")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.FeatureSelection)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.line_3 = QtWidgets.QFrame(self.FeatureSelection)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        self.label_7 = QtWidgets.QLabel(self.FeatureSelection)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_11 = QtWidgets.QLabel(self.FeatureSelection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.FeatureSelection)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 2, 0, 1, 1)
        self.p_select_feat = QtWidgets.QComboBox(self.FeatureSelection)
        self.p_select_feat.setObjectName("p_select_feat")
        self.gridLayout_3.addWidget(self.p_select_feat, 0, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.FeatureSelection)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 1, 0, 1, 1)
        self.p_keywords_include = QtWidgets.QLineEdit(self.FeatureSelection)
        self.p_keywords_include.setObjectName("p_keywords_include")
        self.gridLayout_3.addWidget(self.p_keywords_include, 1, 2, 1, 1)
        self.p_keywords_exclude = QtWidgets.QLineEdit(self.FeatureSelection)
        self.p_keywords_exclude.setObjectName("p_keywords_exclude")
        self.gridLayout_3.addWidget(self.p_keywords_exclude, 2, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.verticalLayout_3.addWidget(self.FeatureSelection)
        self.FilterTrajectories = QtWidgets.QWidget(self.centralwidget)
        self.FilterTrajectories.setObjectName("FilterTrajectories")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.FilterTrajectories)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.line_4 = QtWidgets.QFrame(self.FilterTrajectories)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_5.addWidget(self.line_4)
        self.label_12 = QtWidgets.QLabel(self.FilterTrajectories)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_5.addWidget(self.label_12)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.p_filter_width_max = QtWidgets.QLineEdit(self.FilterTrajectories)
        self.p_filter_width_max.setObjectName("p_filter_width_max")
        self.gridLayout_6.addWidget(self.p_filter_width_max, 4, 2, 1, 1)
        self.p_filter_width_min = QtWidgets.QLineEdit(self.FilterTrajectories)
        self.p_filter_width_min.setObjectName("p_filter_width_min")
        self.gridLayout_6.addWidget(self.p_filter_width_min, 4, 1, 1, 1)
        self.p_filter_length_min = QtWidgets.QLineEdit(self.FilterTrajectories)
        self.p_filter_length_min.setObjectName("p_filter_length_min")
        self.gridLayout_6.addWidget(self.p_filter_length_min, 3, 1, 1, 1)
        self.p_filter_length_max = QtWidgets.QLineEdit(self.FilterTrajectories)
        self.p_filter_length_max.setObjectName("p_filter_length_max")
        self.gridLayout_6.addWidget(self.p_filter_length_max, 3, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.FilterTrajectories)
        self.label_15.setObjectName("label_15")
        self.gridLayout_6.addWidget(self.label_15, 0, 2, 1, 1)
        self.filter_width_units = QtWidgets.QComboBox(self.FilterTrajectories)
        self.filter_width_units.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filter_width_units.sizePolicy().hasHeightForWidth())
        self.filter_width_units.setSizePolicy(sizePolicy)
        self.filter_width_units.setObjectName("filter_width_units")
        self.filter_width_units.addItem("")
        self.filter_width_units.addItem("")
        self.gridLayout_6.addWidget(self.filter_width_units, 4, 3, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.FilterTrajectories)
        self.label_13.setObjectName("label_13")
        self.gridLayout_6.addWidget(self.label_13, 1, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.FilterTrajectories)
        self.label_14.setObjectName("label_14")
        self.gridLayout_6.addWidget(self.label_14, 0, 1, 1, 1)
        self.filter_length_units = QtWidgets.QComboBox(self.FilterTrajectories)
        self.filter_length_units.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filter_length_units.sizePolicy().hasHeightForWidth())
        self.filter_length_units.setSizePolicy(sizePolicy)
        self.filter_length_units.setObjectName("filter_length_units")
        self.filter_length_units.addItem("")
        self.filter_length_units.addItem("")
        self.gridLayout_6.addWidget(self.filter_length_units, 3, 3, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.FilterTrajectories)
        self.label_17.setObjectName("label_17")
        self.gridLayout_6.addWidget(self.label_17, 4, 0, 1, 1)
        self.p_filter_time_units = QtWidgets.QComboBox(self.FilterTrajectories)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p_filter_time_units.sizePolicy().hasHeightForWidth())
        self.p_filter_time_units.setSizePolicy(sizePolicy)
        self.p_filter_time_units.setObjectName("p_filter_time_units")
        self.gridLayout_6.addWidget(self.p_filter_time_units, 1, 3, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.FilterTrajectories)
        self.label_16.setObjectName("label_16")
        self.gridLayout_6.addWidget(self.label_16, 3, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.FilterTrajectories)
        self.label_18.setObjectName("label_18")
        self.gridLayout_6.addWidget(self.label_18, 0, 3, 1, 1)
        self.p_filter_time_min = QtWidgets.QLineEdit(self.FilterTrajectories)
        self.p_filter_time_min.setObjectName("p_filter_time_min")
        self.gridLayout_6.addWidget(self.p_filter_time_min, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.FilterTrajectories)
        self.label_10.setObjectName("label_10")
        self.gridLayout_6.addWidget(self.label_10, 2, 0, 1, 1)
        self.p_filter_travel_min = QtWidgets.QLineEdit(self.FilterTrajectories)
        self.p_filter_travel_min.setObjectName("p_filter_travel_min")
        self.gridLayout_6.addWidget(self.p_filter_travel_min, 2, 1, 1, 1)
        self.p_filter_distance_units = QtWidgets.QComboBox(self.FilterTrajectories)
        self.p_filter_distance_units.setObjectName("p_filter_distance_units")
        self.gridLayout_6.addWidget(self.p_filter_distance_units, 2, 3, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_6)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_19 = QtWidgets.QLabel(self.FilterTrajectories)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout.addWidget(self.label_19)
        self.lineEdit = QtWidgets.QLineEdit(self.FilterTrajectories)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addWidget(self.FilterTrajectories)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_3.addWidget(self.line_2)
        self.p_abbreviate_features = QtWidgets.QCheckBox(self.centralwidget)
        self.p_abbreviate_features.setObjectName("p_abbreviate_features")
        self.verticalLayout_3.addWidget(self.p_abbreviate_features)
        self.p_dorsal_side_known = QtWidgets.QCheckBox(self.centralwidget)
        self.p_dorsal_side_known.setObjectName("p_dorsal_side_known")
        self.verticalLayout_3.addWidget(self.p_dorsal_side_known)
        self.pushButton_start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start.setObjectName("pushButton_start")
        self.verticalLayout_3.addWidget(self.pushButton_start)
        Summarizer.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Summarizer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 729, 22))
        self.menubar.setObjectName("menubar")
        Summarizer.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Summarizer)
        self.statusbar.setObjectName("statusbar")
        Summarizer.setStatusBar(self.statusbar)

        self.retranslateUi(Summarizer)
        QtCore.QMetaObject.connectSlotsByName(Summarizer)

    def retranslateUi(self, Summarizer):
        _translate = QtCore.QCoreApplication.translate
        Summarizer.setWindowTitle(_translate("Summarizer", "MainWindow"))
        self.label_5.setText(_translate("Summarizer", "Summary Type"))
        self.p_is_manual_index.setText(_translate("Summarizer", "Use manually \n"
"edited trajectories?"))
        self.label_4.setText(_translate("Summarizer", "Features Type"))
        self.pushButton_rootdir.setText(_translate("Summarizer", "Root  Directory"))
        self.label_2.setText(_translate("Summarizer", "Fraction of trajectories\n"
" to sample"))
        self.label.setText(_translate("Summarizer", "Number of Folds"))
        self.label_3.setText(_translate("Summarizer", "Time (seconds)\n"
" to sample"))
        self.label_6.setText(_translate("Summarizer", "Time windows (optional)"))
        self.p_time_windows.setText(_translate("Summarizer", "0:end"))
        self.label_7.setText(_translate("Summarizer", "Feature selection (optional)"))
        self.label_11.setText(_translate("Summarizer", "Feature set"))
        self.label_9.setText(_translate("Summarizer", "Exclude keywords"))
        self.label_8.setText(_translate("Summarizer", "Include keywords"))
        self.label_12.setText(_translate("Summarizer", "Trajectories filtering options (optional)"))
        self.p_filter_width_min.setText(_translate("Summarizer", "0"))
        self.p_filter_length_min.setText(_translate("Summarizer", "0"))
        self.label_15.setText(_translate("Summarizer", "Max accepted"))
        self.filter_width_units.setItemText(0, _translate("Summarizer", "pixels"))
        self.filter_width_units.setItemText(1, _translate("Summarizer", "microns"))
        self.label_13.setText(_translate("Summarizer", "Trajectory duration"))
        self.label_14.setText(_translate("Summarizer", "Min accepted"))
        self.filter_length_units.setItemText(0, _translate("Summarizer", "pixels"))
        self.filter_length_units.setItemText(1, _translate("Summarizer", "microns"))
        self.label_17.setText(_translate("Summarizer", "Mean worm width"))
        self.label_16.setText(_translate("Summarizer", "Mean worm length"))
        self.label_18.setText(_translate("Summarizer", "Units"))
        self.p_filter_time_min.setText(_translate("Summarizer", "0"))
        self.label_10.setText(_translate("Summarizer", "Total distance traveled"))
        self.p_filter_travel_min.setText(_translate("Summarizer", "0"))
        self.label_19.setText(_translate("Summarizer", "More filtering options from file"))
        self.p_abbreviate_features.setText(_translate("Summarizer", "Abbreviate feature names"))
        self.p_dorsal_side_known.setText(_translate("Summarizer", "Dorsal side annotated"))
        self.pushButton_start.setText(_translate("Summarizer", "START"))

