mex chainCodeLength2Index.cpp		
mex cleanSkeletonMex.cpp			
mex curvatureMex.cpp			
mex minPeaksCircDist.cpp
mex circComputeChainCodeLengthsMex.cpp	
mex cleanWormHelperMex.cpp			
mex curvspaceMex.cpp			
mex skeletonizeMex.cpp
mex circCurvatureMex.cpp			
mex computeChainCodeLengthsMex.cpp		
mex maxPeaksCircDist.cpp