# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GetMaskParams.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_GetMaskParams(object):
    def setupUi(self, GetMaskParams):
        GetMaskParams.setObjectName("GetMaskParams")
        GetMaskParams.resize(1224, 811)
        self.centralWidget = QtWidgets.QWidget(GetMaskParams)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_mask = QtWidgets.QWidget()
        self.tab_mask.setObjectName("tab_mask")
        self.layoutWidget = QtWidgets.QWidget(self.tab_mask)
        self.layoutWidget.setGeometry(QtCore.QRect(-5, 10, 237, 691))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.dial_min_area = QtWidgets.QDial(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dial_min_area.sizePolicy().hasHeightForWidth())
        self.dial_min_area.setSizePolicy(sizePolicy)
        self.dial_min_area.setMaximum(10000)
        self.dial_min_area.setProperty("value", 100)
        self.dial_min_area.setObjectName("dial_min_area")
        self.gridLayout_3.addWidget(self.dial_min_area, 1, 1, 1, 1)
        self.checkBox_isLightBgnd = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_isLightBgnd.setChecked(True)
        self.checkBox_isLightBgnd.setObjectName("checkBox_isLightBgnd")
        self.gridLayout_3.addWidget(self.checkBox_isLightBgnd, 9, 0, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 5, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.spinBox_min_area = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_min_area.setMaximum(10000000)
        self.spinBox_min_area.setProperty("value", 100)
        self.spinBox_min_area.setObjectName("spinBox_min_area")
        self.verticalLayout.addWidget(self.spinBox_min_area)
        self.gridLayout_3.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.dial_block_size = QtWidgets.QDial(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dial_block_size.sizePolicy().hasHeightForWidth())
        self.dial_block_size.setSizePolicy(sizePolicy)
        self.dial_block_size.setMinimum(5)
        self.dial_block_size.setMaximum(200)
        self.dial_block_size.setProperty("value", 61)
        self.dial_block_size.setObjectName("dial_block_size")
        self.gridLayout_3.addWidget(self.dial_block_size, 4, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.spinBox_max_area = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_max_area.setMinimum(100)
        self.spinBox_max_area.setMaximum(10000000)
        self.spinBox_max_area.setProperty("value", 5000)
        self.spinBox_max_area.setObjectName("spinBox_max_area")
        self.verticalLayout_2.addWidget(self.spinBox_max_area)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 2, 0, 1, 1)
        self.spinBox_fps = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.spinBox_fps.setProperty("value", 25.0)
        self.spinBox_fps.setObjectName("spinBox_fps")
        self.gridLayout_3.addWidget(self.spinBox_fps, 7, 1, 1, 1)
        self.dial_thresh_C = QtWidgets.QDial(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dial_thresh_C.sizePolicy().hasHeightForWidth())
        self.dial_thresh_C.setSizePolicy(sizePolicy)
        self.dial_thresh_C.setMinimum(5)
        self.dial_thresh_C.setMaximum(100)
        self.dial_thresh_C.setProperty("value", 15)
        self.dial_thresh_C.setObjectName("dial_thresh_C")
        self.gridLayout_3.addWidget(self.dial_thresh_C, 3, 1, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.spinBox_thresh_C = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_thresh_C.setMinimum(-100)
        self.spinBox_thresh_C.setMaximum(100)
        self.spinBox_thresh_C.setProperty("value", 15)
        self.spinBox_thresh_C.setObjectName("spinBox_thresh_C")
        self.verticalLayout_4.addWidget(self.spinBox_thresh_C)
        self.gridLayout_3.addLayout(self.verticalLayout_4, 3, 0, 1, 1)
        self.pushButton_moreParams = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_moreParams.setObjectName("pushButton_moreParams")
        self.gridLayout_3.addWidget(self.pushButton_moreParams, 11, 0, 1, 2)
        self.checkBox_keepBorderData = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_keepBorderData.setObjectName("checkBox_keepBorderData")
        self.gridLayout_3.addWidget(self.checkBox_keepBorderData, 10, 0, 1, 2)
        self.label_fps = QtWidgets.QLabel(self.layoutWidget)
        self.label_fps.setObjectName("label_fps")
        self.gridLayout_3.addWidget(self.label_fps, 7, 0, 1, 1)
        self.spinBox_dilation_size = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_dilation_size.setMinimum(1)
        self.spinBox_dilation_size.setMaximum(999)
        self.spinBox_dilation_size.setProperty("value", 9)
        self.spinBox_dilation_size.setObjectName("spinBox_dilation_size")
        self.gridLayout_3.addWidget(self.spinBox_dilation_size, 5, 1, 1, 1)
        self.dial_max_area = QtWidgets.QDial(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dial_max_area.sizePolicy().hasHeightForWidth())
        self.dial_max_area.setSizePolicy(sizePolicy)
        self.dial_max_area.setMinimum(100)
        self.dial_max_area.setMaximum(100000)
        self.dial_max_area.setProperty("value", 5000)
        self.dial_max_area.setObjectName("dial_max_area")
        self.gridLayout_3.addWidget(self.dial_max_area, 2, 1, 1, 1)
        self.spinBox_buff_size = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_buff_size.setMinimum(1)
        self.spinBox_buff_size.setMaximum(1000)
        self.spinBox_buff_size.setProperty("value", 25)
        self.spinBox_buff_size.setObjectName("spinBox_buff_size")
        self.gridLayout_3.addWidget(self.spinBox_buff_size, 8, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 8, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.spinBox_block_size = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_block_size.setMinimum(5)
        self.spinBox_block_size.setMaximum(1000000)
        self.spinBox_block_size.setProperty("value", 61)
        self.spinBox_block_size.setObjectName("spinBox_block_size")
        self.verticalLayout_3.addWidget(self.spinBox_block_size)
        self.gridLayout_3.addLayout(self.verticalLayout_3, 4, 0, 1, 1)
        self.tabWidget.addTab(self.tab_mask, "")
        self.tab_background = QtWidgets.QWidget()
        self.tab_background.setObjectName("tab_background")
        self.checkBox_subtractBackground = QtWidgets.QCheckBox(self.tab_background)
        self.checkBox_subtractBackground.setGeometry(QtCore.QRect(10, 20, 161, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_subtractBackground.sizePolicy().hasHeightForWidth())
        self.checkBox_subtractBackground.setSizePolicy(sizePolicy)
        self.checkBox_subtractBackground.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_subtractBackground.setObjectName("checkBox_subtractBackground")
        self.label_backgroundThreshold = QtWidgets.QLabel(self.tab_background)
        self.label_backgroundThreshold.setGeometry(QtCore.QRect(14, 80, 71, 16))
        self.label_backgroundThreshold.setObjectName("label_backgroundThreshold")
        self.spinBox_backgroundThreshold = QtWidgets.QSpinBox(self.tab_background)
        self.spinBox_backgroundThreshold.setGeometry(QtCore.QRect(133, 76, 90, 24))
        self.spinBox_backgroundThreshold.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_backgroundThreshold.setMaximum(255)
        self.spinBox_backgroundThreshold.setProperty("value", 15)
        self.spinBox_backgroundThreshold.setObjectName("spinBox_backgroundThreshold")
        self.checkBox_ignoreMask = QtWidgets.QCheckBox(self.tab_background)
        self.checkBox_ignoreMask.setGeometry(QtCore.QRect(10, 47, 151, 20))
        self.checkBox_ignoreMask.setObjectName("checkBox_ignoreMask")
        self.label_backgroundFrameOffset = QtWidgets.QLabel(self.tab_background)
        self.label_backgroundFrameOffset.setGeometry(QtCore.QRect(34, 140, 91, 16))
        self.label_backgroundFrameOffset.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_backgroundFrameOffset.setObjectName("label_backgroundFrameOffset")
        self.spinBox_backgroundFrameOffset = QtWidgets.QSpinBox(self.tab_background)
        self.spinBox_backgroundFrameOffset.setGeometry(QtCore.QRect(132, 137, 90, 24))
        self.spinBox_backgroundFrameOffset.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_backgroundFrameOffset.setMaximum(100000)
        self.spinBox_backgroundFrameOffset.setProperty("value", 500)
        self.spinBox_backgroundFrameOffset.setObjectName("spinBox_backgroundFrameOffset")
        self.label_backgroundGenerationFunction = QtWidgets.QLabel(self.tab_background)
        self.label_backgroundGenerationFunction.setGeometry(QtCore.QRect(62, 171, 61, 16))
        self.label_backgroundGenerationFunction.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_backgroundGenerationFunction.setObjectName("label_backgroundGenerationFunction")
        self.radioButton_backgroundGenerationFunction_maximum = QtWidgets.QRadioButton(self.tab_background)
        self.radioButton_backgroundGenerationFunction_maximum.setGeometry(QtCore.QRect(132, 189, 100, 20))
        self.radioButton_backgroundGenerationFunction_maximum.setChecked(True)
        self.radioButton_backgroundGenerationFunction_maximum.setObjectName("radioButton_backgroundGenerationFunction_maximum")
        self.buttonGroup_backgroundGenerationFunction = QtWidgets.QButtonGroup(GetMaskParams)
        self.buttonGroup_backgroundGenerationFunction.setObjectName("buttonGroup_backgroundGenerationFunction")
        self.buttonGroup_backgroundGenerationFunction.addButton(self.radioButton_backgroundGenerationFunction_maximum)
        self.radioButton_backgroundGenerationFunction_minimum = QtWidgets.QRadioButton(self.tab_background)
        self.radioButton_backgroundGenerationFunction_minimum.setGeometry(QtCore.QRect(132, 169, 100, 20))
        self.radioButton_backgroundGenerationFunction_minimum.setChecked(False)
        self.radioButton_backgroundGenerationFunction_minimum.setObjectName("radioButton_backgroundGenerationFunction_minimum")
        self.buttonGroup_backgroundGenerationFunction.addButton(self.radioButton_backgroundGenerationFunction_minimum)
        self.pushButton_backgroundFile = QtWidgets.QPushButton(self.tab_background)
        self.pushButton_backgroundFile.setGeometry(QtCore.QRect(21, 239, 71, 32))
        self.pushButton_backgroundFile.setObjectName("pushButton_backgroundFile")
        self.label_backgroundFile = QtWidgets.QLabel(self.tab_background)
        self.label_backgroundFile.setGeometry(QtCore.QRect(31, 269, 191, 101))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_backgroundFile.setFont(font)
        self.label_backgroundFile.setScaledContents(True)
        self.label_backgroundFile.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_backgroundFile.setWordWrap(True)
        self.label_backgroundFile.setObjectName("label_backgroundFile")
        self.toolButton_clearBackgroundFile = QtWidgets.QToolButton(self.tab_background)
        self.toolButton_clearBackgroundFile.setGeometry(QtCore.QRect(91, 246, 16, 16))
        self.toolButton_clearBackgroundFile.setObjectName("toolButton_clearBackgroundFile")
        self.radioButton_backgroundType_dynamic = QtWidgets.QRadioButton(self.tab_background)
        self.radioButton_backgroundType_dynamic.setGeometry(QtCore.QRect(7, 110, 161, 20))
        self.radioButton_backgroundType_dynamic.setChecked(True)
        self.radioButton_backgroundType_dynamic.setObjectName("radioButton_backgroundType_dynamic")
        self.buttonGroup_backgroundType = QtWidgets.QButtonGroup(GetMaskParams)
        self.buttonGroup_backgroundType.setObjectName("buttonGroup_backgroundType")
        self.buttonGroup_backgroundType.addButton(self.radioButton_backgroundType_dynamic)
        self.radioButton_backgroundType_file = QtWidgets.QRadioButton(self.tab_background)
        self.radioButton_backgroundType_file.setGeometry(QtCore.QRect(6, 216, 161, 20))
        self.radioButton_backgroundType_file.setObjectName("radioButton_backgroundType_file")
        self.buttonGroup_backgroundType.addButton(self.radioButton_backgroundType_file)
        self.tabWidget.addTab(self.tab_background, "")
        self.tab_analysis = QtWidgets.QWidget()
        self.tab_analysis.setEnabled(True)
        self.tab_analysis.setObjectName("tab_analysis")
        self.radioButton_analysisType_worm = QtWidgets.QRadioButton(self.tab_analysis)
        self.radioButton_analysisType_worm.setGeometry(QtCore.QRect(10, 37, 100, 20))
        self.radioButton_analysisType_worm.setChecked(True)
        self.radioButton_analysisType_worm.setObjectName("radioButton_analysisType_worm")
        self.buttonGroup_analysisType = QtWidgets.QButtonGroup(GetMaskParams)
        self.buttonGroup_analysisType.setObjectName("buttonGroup_analysisType")
        self.buttonGroup_analysisType.addButton(self.radioButton_analysisType_worm)
        self.radioButton_analysisType_zebrafish = QtWidgets.QRadioButton(self.tab_analysis)
        self.radioButton_analysisType_zebrafish.setGeometry(QtCore.QRect(10, 60, 100, 20))
        self.radioButton_analysisType_zebrafish.setObjectName("radioButton_analysisType_zebrafish")
        self.buttonGroup_analysisType.addButton(self.radioButton_analysisType_zebrafish)
        self.label_7 = QtWidgets.QLabel(self.tab_analysis)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 121, 16))
        self.label_7.setStyleSheet("font-weight: bold;")
        self.label_7.setObjectName("label_7")
        self.groupBox_zebrafishOptions = QtWidgets.QGroupBox(self.tab_analysis)
        self.groupBox_zebrafishOptions.setGeometry(QtCore.QRect(0, 120, 231, 591))
        self.groupBox_zebrafishOptions.setObjectName("groupBox_zebrafishOptions")
        self.spinBox_zf_tailLength = QtWidgets.QSpinBox(self.groupBox_zebrafishOptions)
        self.spinBox_zf_tailLength.setEnabled(False)
        self.spinBox_zf_tailLength.setGeometry(QtCore.QRect(169, 152, 51, 24))
        self.spinBox_zf_tailLength.setMaximum(500)
        self.spinBox_zf_tailLength.setProperty("value", 60)
        self.spinBox_zf_tailLength.setObjectName("spinBox_zf_tailLength")
        self.label_zf_tailLength = QtWidgets.QLabel(self.groupBox_zebrafishOptions)
        self.label_zf_tailLength.setEnabled(False)
        self.label_zf_tailLength.setGeometry(QtCore.QRect(9, 152, 121, 16))
        self.label_zf_tailLength.setObjectName("label_zf_tailLength")
        self.spinBox_zf_minAngle = QtWidgets.QSpinBox(self.groupBox_zebrafishOptions)
        self.spinBox_zf_minAngle.setGeometry(QtCore.QRect(168, 29, 51, 24))
        self.spinBox_zf_minAngle.setMinimum(-180)
        self.spinBox_zf_minAngle.setMaximum(180)
        self.spinBox_zf_minAngle.setProperty("value", -90)
        self.spinBox_zf_minAngle.setObjectName("spinBox_zf_minAngle")
        self.label_10 = QtWidgets.QLabel(self.groupBox_zebrafishOptions)
        self.label_10.setGeometry(QtCore.QRect(8, 59, 121, 16))
        self.label_10.setObjectName("label_10")
        self.spinBox_zf_maxAngle = QtWidgets.QSpinBox(self.groupBox_zebrafishOptions)
        self.spinBox_zf_maxAngle.setGeometry(QtCore.QRect(168, 59, 51, 24))
        self.spinBox_zf_maxAngle.setMinimum(-90)
        self.spinBox_zf_maxAngle.setMaximum(90)
        self.spinBox_zf_maxAngle.setProperty("value", 90)
        self.spinBox_zf_maxAngle.setObjectName("spinBox_zf_maxAngle")
        self.label_9 = QtWidgets.QLabel(self.groupBox_zebrafishOptions)
        self.label_9.setGeometry(QtCore.QRect(8, 29, 121, 16))
        self.label_9.setObjectName("label_9")
        self.spinBox_zf_numberOfSegments = QtWidgets.QSpinBox(self.groupBox_zebrafishOptions)
        self.spinBox_zf_numberOfSegments.setEnabled(False)
        self.spinBox_zf_numberOfSegments.setGeometry(QtCore.QRect(169, 182, 51, 24))
        self.spinBox_zf_numberOfSegments.setMinimum(1)
        self.spinBox_zf_numberOfSegments.setProperty("value", 12)
        self.spinBox_zf_numberOfSegments.setObjectName("spinBox_zf_numberOfSegments")
        self.label_11 = QtWidgets.QLabel(self.groupBox_zebrafishOptions)
        self.label_11.setGeometry(QtCore.QRect(8, 89, 121, 16))
        self.label_11.setObjectName("label_11")
        self.label_zf_numberOfSegments = QtWidgets.QLabel(self.groupBox_zebrafishOptions)
        self.label_zf_numberOfSegments.setEnabled(False)
        self.label_zf_numberOfSegments.setGeometry(QtCore.QRect(9, 182, 131, 16))
        self.label_zf_numberOfSegments.setObjectName("label_zf_numberOfSegments")
        self.spinBox_zf_anglesPerSegment = QtWidgets.QSpinBox(self.groupBox_zebrafishOptions)
        self.spinBox_zf_anglesPerSegment.setGeometry(QtCore.QRect(168, 89, 51, 24))
        self.spinBox_zf_anglesPerSegment.setMaximum(180)
        self.spinBox_zf_anglesPerSegment.setProperty("value", 180)
        self.spinBox_zf_anglesPerSegment.setObjectName("spinBox_zf_anglesPerSegment")
        self.spinBox_zf_segmentDrawWidth = QtWidgets.QSpinBox(self.groupBox_zebrafishOptions)
        self.spinBox_zf_segmentDrawWidth.setGeometry(QtCore.QRect(169, 242, 51, 24))
        self.spinBox_zf_segmentDrawWidth.setMinimum(1)
        self.spinBox_zf_segmentDrawWidth.setProperty("value", 2)
        self.spinBox_zf_segmentDrawWidth.setObjectName("spinBox_zf_segmentDrawWidth")
        self.label_14 = QtWidgets.QLabel(self.groupBox_zebrafishOptions)
        self.label_14.setGeometry(QtCore.QRect(9, 284, 191, 16))
        self.label_14.setObjectName("label_14")
        self.spinBox_zf_segmentTestWidth = QtWidgets.QSpinBox(self.groupBox_zebrafishOptions)
        self.spinBox_zf_segmentTestWidth.setEnabled(False)
        self.spinBox_zf_segmentTestWidth.setGeometry(QtCore.QRect(169, 212, 51, 24))
        self.spinBox_zf_segmentTestWidth.setMinimum(1)
        self.spinBox_zf_segmentTestWidth.setProperty("value", 2)
        self.spinBox_zf_segmentTestWidth.setObjectName("spinBox_zf_segmentTestWidth")
        self.label_15 = QtWidgets.QLabel(self.groupBox_zebrafishOptions)
        self.label_15.setGeometry(QtCore.QRect(9, 362, 141, 16))
        self.label_15.setObjectName("label_15")
        self.label_zf_segmentDrawWidth = QtWidgets.QLabel(self.groupBox_zebrafishOptions)
        self.label_zf_segmentDrawWidth.setGeometry(QtCore.QRect(9, 246, 151, 16))
        self.label_zf_segmentDrawWidth.setObjectName("label_zf_segmentDrawWidth")
        self.label_zf_segmentTestWidth = QtWidgets.QLabel(self.groupBox_zebrafishOptions)
        self.label_zf_segmentTestWidth.setEnabled(False)
        self.label_zf_segmentTestWidth.setGeometry(QtCore.QRect(9, 215, 141, 16))
        self.label_zf_segmentTestWidth.setObjectName("label_zf_segmentTestWidth")
        self.radioButton_zf_tailDetection_modelEndPoint = QtWidgets.QRadioButton(self.groupBox_zebrafishOptions)
        self.radioButton_zf_tailDetection_modelEndPoint.setGeometry(QtCore.QRect(29, 304, 141, 20))
        self.radioButton_zf_tailDetection_modelEndPoint.setChecked(True)
        self.radioButton_zf_tailDetection_modelEndPoint.setObjectName("radioButton_zf_tailDetection_modelEndPoint")
        self.buttonGroup_zf_tailPointDetectionAlgorithm = QtWidgets.QButtonGroup(GetMaskParams)
        self.buttonGroup_zf_tailPointDetectionAlgorithm.setObjectName("buttonGroup_zf_tailPointDetectionAlgorithm")
        self.buttonGroup_zf_tailPointDetectionAlgorithm.addButton(self.radioButton_zf_tailDetection_modelEndPoint)
        self.radioButton_zf_tailDetection_maximumCurvature = QtWidgets.QRadioButton(self.groupBox_zebrafishOptions)
        self.radioButton_zf_tailDetection_maximumCurvature.setGeometry(QtCore.QRect(29, 326, 151, 20))
        self.radioButton_zf_tailDetection_maximumCurvature.setObjectName("radioButton_zf_tailDetection_maximumCurvature")
        self.buttonGroup_zf_tailPointDetectionAlgorithm.addButton(self.radioButton_zf_tailDetection_maximumCurvature)
        self.spinBox_zf_pruneRetention = QtWidgets.QSpinBox(self.groupBox_zebrafishOptions)
        self.spinBox_zf_pruneRetention.setGeometry(QtCore.QRect(169, 359, 51, 24))
        self.spinBox_zf_pruneRetention.setMinimum(1)
        self.spinBox_zf_pruneRetention.setMaximum(1000)
        self.spinBox_zf_pruneRetention.setProperty("value", 1)
        self.spinBox_zf_pruneRetention.setObjectName("spinBox_zf_pruneRetention")
        self.checkBox_autoDetectTailLength = QtWidgets.QCheckBox(self.groupBox_zebrafishOptions)
        self.checkBox_autoDetectTailLength.setGeometry(QtCore.QRect(8, 120, 171, 20))
        self.checkBox_autoDetectTailLength.setChecked(True)
        self.checkBox_autoDetectTailLength.setObjectName("checkBox_autoDetectTailLength")
        self.tabWidget.addTab(self.tab_analysis, "")
        self.horizontalLayout_5.addWidget(self.tabWidget)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.graphicsView_full = QtWidgets.QGraphicsView(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView_full.sizePolicy().hasHeightForWidth())
        self.graphicsView_full.setSizePolicy(sizePolicy)
        self.graphicsView_full.setDragMode(QtWidgets.QGraphicsView.ScrollHandDrag)
        self.graphicsView_full.setTransformationAnchor(QtWidgets.QGraphicsView.AnchorUnderMouse)
        self.graphicsView_full.setResizeAnchor(QtWidgets.QGraphicsView.AnchorViewCenter)
        self.graphicsView_full.setObjectName("graphicsView_full")
        self.horizontalLayout_2.addWidget(self.graphicsView_full)
        self.graphicsView_mask = QtWidgets.QGraphicsView(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView_mask.sizePolicy().hasHeightForWidth())
        self.graphicsView_mask.setSizePolicy(sizePolicy)
        self.graphicsView_mask.setDragMode(QtWidgets.QGraphicsView.ScrollHandDrag)
        self.graphicsView_mask.setTransformationAnchor(QtWidgets.QGraphicsView.AnchorUnderMouse)
        self.graphicsView_mask.setResizeAnchor(QtWidgets.QGraphicsView.AnchorViewCenter)
        self.graphicsView_mask.setObjectName("graphicsView_mask")
        self.horizontalLayout_2.addWidget(self.graphicsView_mask)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.widget = QtWidgets.QWidget(self.centralWidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_video = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_video.sizePolicy().hasHeightForWidth())
        self.pushButton_video.setSizePolicy(sizePolicy)
        self.pushButton_video.setObjectName("pushButton_video")
        self.gridLayout.addWidget(self.pushButton_video, 0, 0, 1, 1)
        self.lineEdit_results = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_results.setObjectName("lineEdit_results")
        self.gridLayout.addWidget(self.lineEdit_results, 2, 1, 1, 1)
        self.lineEdit_video = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_video.setObjectName("lineEdit_video")
        self.gridLayout.addWidget(self.lineEdit_video, 0, 1, 1, 1)
        self.lineEdit_mask = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_mask.setReadOnly(False)
        self.lineEdit_mask.setObjectName("lineEdit_mask")
        self.gridLayout.addWidget(self.lineEdit_mask, 3, 1, 1, 1)
        self.pushButton_mask = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_mask.sizePolicy().hasHeightForWidth())
        self.pushButton_mask.setSizePolicy(sizePolicy)
        self.pushButton_mask.setObjectName("pushButton_mask")
        self.gridLayout.addWidget(self.pushButton_mask, 3, 0, 1, 1)
        self.pushButton_paramFile = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_paramFile.sizePolicy().hasHeightForWidth())
        self.pushButton_paramFile.setSizePolicy(sizePolicy)
        self.pushButton_paramFile.setObjectName("pushButton_paramFile")
        self.gridLayout.addWidget(self.pushButton_paramFile, 1, 0, 1, 1)
        self.lineEdit_paramFile = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_paramFile.setObjectName("lineEdit_paramFile")
        self.gridLayout.addWidget(self.lineEdit_paramFile, 1, 1, 1, 1)
        self.pushButton_results = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_results.sizePolicy().hasHeightForWidth())
        self.pushButton_results.setSizePolicy(sizePolicy)
        self.pushButton_results.setObjectName("pushButton_results")
        self.gridLayout.addWidget(self.pushButton_results, 2, 0, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton_next = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_next.sizePolicy().hasHeightForWidth())
        self.pushButton_next.setSizePolicy(sizePolicy)
        self.pushButton_next.setObjectName("pushButton_next")
        self.verticalLayout_6.addWidget(self.pushButton_next)
        self.pushButton_saveParam = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_saveParam.sizePolicy().hasHeightForWidth())
        self.pushButton_saveParam.setSizePolicy(sizePolicy)
        self.pushButton_saveParam.setObjectName("pushButton_saveParam")
        self.verticalLayout_6.addWidget(self.pushButton_saveParam)
        self.pushButton_start = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_start.sizePolicy().hasHeightForWidth())
        self.pushButton_start.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButton_start.setFont(font)
        self.pushButton_start.setMouseTracking(False)
        self.pushButton_start.setAutoFillBackground(False)
        self.pushButton_start.setCheckable(False)
        self.pushButton_start.setAutoDefault(False)
        self.pushButton_start.setDefault(False)
        self.pushButton_start.setFlat(False)
        self.pushButton_start.setObjectName("pushButton_start")
        self.verticalLayout_6.addWidget(self.pushButton_start)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.horizontalLayout_4.addWidget(self.widget)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5.addLayout(self.verticalLayout_7)
        self.horizontalLayout_5.setStretch(1, 8)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        GetMaskParams.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(GetMaskParams)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1224, 22))
        self.menuBar.setObjectName("menuBar")
        GetMaskParams.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(GetMaskParams)
        self.mainToolBar.setObjectName("mainToolBar")
        GetMaskParams.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(GetMaskParams)
        self.statusBar.setObjectName("statusBar")
        GetMaskParams.setStatusBar(self.statusBar)

        self.retranslateUi(GetMaskParams)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(GetMaskParams)

    def retranslateUi(self, GetMaskParams):
        _translate = QtCore.QCoreApplication.translate
        GetMaskParams.setWindowTitle(_translate("GetMaskParams", "GetMaskParams"))
        self.checkBox_isLightBgnd.setText(_translate("GetMaskParams", "is light background?"))
        self.label_6.setText(_translate("GetMaskParams", "Dilation"))
        self.label.setText(_translate("GetMaskParams", "Min Area"))
        self.label_4.setText(_translate("GetMaskParams", "Max Area"))
        self.label_2.setText(_translate("GetMaskParams", "Thresh_C"))
        self.pushButton_moreParams.setText(_translate("GetMaskParams", "Edit more parameters"))
        self.checkBox_keepBorderData.setText(_translate("GetMaskParams", "keep border data?"))
        self.label_fps.setText(_translate("GetMaskParams", "Expected FPS"))
        self.label_5.setText(_translate("GetMaskParams", "Frames to average"))
        self.label_3.setText(_translate("GetMaskParams", "Block Size"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_mask), _translate("GetMaskParams", "Mask"))
        self.checkBox_subtractBackground.setText(_translate("GetMaskParams", "Subtract Background"))
        self.label_backgroundThreshold.setText(_translate("GetMaskParams", "Tolerance"))
        self.checkBox_ignoreMask.setText(_translate("GetMaskParams", "Ignore Mask"))
        self.label_backgroundFrameOffset.setText(_translate("GetMaskParams", "Frame Offset"))
        self.label_backgroundGenerationFunction.setText(_translate("GetMaskParams", "Function"))
        self.radioButton_backgroundGenerationFunction_maximum.setText(_translate("GetMaskParams", "Maximum"))
        self.radioButton_backgroundGenerationFunction_minimum.setText(_translate("GetMaskParams", "Minimum"))
        self.pushButton_backgroundFile.setText(_translate("GetMaskParams", "Select"))
        self.label_backgroundFile.setText(_translate("GetMaskParams", "None"))
        self.toolButton_clearBackgroundFile.setText(_translate("GetMaskParams", "x"))
        self.radioButton_backgroundType_dynamic.setText(_translate("GetMaskParams", "Generate dynamically"))
        self.radioButton_backgroundType_file.setText(_translate("GetMaskParams", "From file"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_background), _translate("GetMaskParams", "Background"))
        self.radioButton_analysisType_worm.setText(_translate("GetMaskParams", "Worm"))
        self.radioButton_analysisType_zebrafish.setText(_translate("GetMaskParams", "Zebrafish"))
        self.label_7.setText(_translate("GetMaskParams", "Analysis Type"))
        self.groupBox_zebrafishOptions.setTitle(_translate("GetMaskParams", "Zebrafish Options"))
        self.label_zf_tailLength.setText(_translate("GetMaskParams", "Tail length"))
        self.label_10.setText(_translate("GetMaskParams", "Segment max angle"))
        self.label_9.setText(_translate("GetMaskParams", "Segment min angle"))
        self.label_11.setText(_translate("GetMaskParams", "Angles per segment"))
        self.label_zf_numberOfSegments.setText(_translate("GetMaskParams", "Number of segments"))
        self.label_14.setText(_translate("GetMaskParams", "Tail point detection algorithm"))
        self.label_15.setText(_translate("GetMaskParams", "Prune retention"))
        self.label_zf_segmentDrawWidth.setText(_translate("GetMaskParams", "Segment draw width"))
        self.label_zf_segmentTestWidth.setText(_translate("GetMaskParams", "Segment test width"))
        self.radioButton_zf_tailDetection_modelEndPoint.setText(_translate("GetMaskParams", "Model end point"))
        self.radioButton_zf_tailDetection_maximumCurvature.setText(_translate("GetMaskParams", "Maximum curvature"))
        self.checkBox_autoDetectTailLength.setText(_translate("GetMaskParams", "Auto-detect tail length"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_analysis), _translate("GetMaskParams", "Analysis"))
        self.pushButton_video.setText(_translate("GetMaskParams", "Video File"))
        self.pushButton_mask.setText(_translate("GetMaskParams", "Mask Dir"))
        self.pushButton_paramFile.setText(_translate("GetMaskParams", "Parameters File"))
        self.pushButton_results.setText(_translate("GetMaskParams", "Results Dir"))
        self.pushButton_next.setText(_translate("GetMaskParams", "Next Chunk"))
        self.pushButton_saveParam.setText(_translate("GetMaskParams", "Save Parameters"))
        self.pushButton_start.setText(_translate("GetMaskParams", "Start Analysis"))

