# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GetMaskParams.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_GetMaskParams(object):
    def setupUi(self, GetMaskParams):
        GetMaskParams.setObjectName("GetMaskParams")
        GetMaskParams.resize(986, 658)
        self.centralWidget = QtWidgets.QWidget(GetMaskParams)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_mask = QtWidgets.QWidget()
        self.tab_mask.setObjectName("tab_mask")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_mask)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_thresh_C = QtWidgets.QLabel(self.tab_mask)
        self.label_thresh_C.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_thresh_C.setObjectName("label_thresh_C")
        self.gridLayout_3.addWidget(self.label_thresh_C, 4, 2, 1, 1)
        self.horizontalSlider_min_area = QtWidgets.QSlider(self.tab_mask)
        self.horizontalSlider_min_area.setMaximum(10000)
        self.horizontalSlider_min_area.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_min_area.setObjectName("horizontalSlider_min_area")
        self.gridLayout_3.addWidget(self.horizontalSlider_min_area, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab_mask)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 8, 1, 1, 1)
        self.label_max_aea = QtWidgets.QLabel(self.tab_mask)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_max_aea.sizePolicy().hasHeightForWidth())
        self.label_max_aea.setSizePolicy(sizePolicy)
        self.label_max_aea.setObjectName("label_max_aea")
        self.gridLayout_3.addWidget(self.label_max_aea, 0, 2, 1, 1)
        self.horizontalSlider_thresh_C = QtWidgets.QSlider(self.tab_mask)
        self.horizontalSlider_thresh_C.setMaximum(100)
        self.horizontalSlider_thresh_C.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_thresh_C.setObjectName("horizontalSlider_thresh_C")
        self.gridLayout_3.addWidget(self.horizontalSlider_thresh_C, 5, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 3, 1, 1, 2)
        self.horizontalSlider_max_area = QtWidgets.QSlider(self.tab_mask)
        self.horizontalSlider_max_area.setMinimum(0)
        self.horizontalSlider_max_area.setMaximum(100000)
        self.horizontalSlider_max_area.setSingleStep(100)
        self.horizontalSlider_max_area.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_max_area.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.horizontalSlider_max_area.setObjectName("horizontalSlider_max_area")
        self.gridLayout_3.addWidget(self.horizontalSlider_max_area, 1, 2, 1, 1)
        self.p_block_size = QtWidgets.QSpinBox(self.tab_mask)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p_block_size.sizePolicy().hasHeightForWidth())
        self.p_block_size.setSizePolicy(sizePolicy)
        self.p_block_size.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.p_block_size.setMinimum(5)
        self.p_block_size.setMaximum(1000000)
        self.p_block_size.setProperty("value", 61)
        self.p_block_size.setObjectName("p_block_size")
        self.gridLayout_3.addWidget(self.p_block_size, 6, 1, 1, 1)
        self.p_thresh_C = QtWidgets.QSpinBox(self.tab_mask)
        self.p_thresh_C.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.p_thresh_C.setMinimum(-100)
        self.p_thresh_C.setMaximum(100)
        self.p_thresh_C.setProperty("value", 15)
        self.p_thresh_C.setObjectName("p_thresh_C")
        self.gridLayout_3.addWidget(self.p_thresh_C, 6, 2, 1, 1)
        self.label_min_area = QtWidgets.QLabel(self.tab_mask)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_min_area.sizePolicy().hasHeightForWidth())
        self.label_min_area.setSizePolicy(sizePolicy)
        self.label_min_area.setObjectName("label_min_area")
        self.gridLayout_3.addWidget(self.label_min_area, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 7, 1, 1, 2)
        self.label_block_size = QtWidgets.QLabel(self.tab_mask)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_block_size.sizePolicy().hasHeightForWidth())
        self.label_block_size.setSizePolicy(sizePolicy)
        self.label_block_size.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_block_size.setObjectName("label_block_size")
        self.gridLayout_3.addWidget(self.label_block_size, 4, 1, 1, 1)
        self.p_dilation_size = QtWidgets.QSpinBox(self.tab_mask)
        self.p_dilation_size.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.p_dilation_size.setMinimum(1)
        self.p_dilation_size.setMaximum(999)
        self.p_dilation_size.setProperty("value", 9)
        self.p_dilation_size.setObjectName("p_dilation_size")
        self.gridLayout_3.addWidget(self.p_dilation_size, 10, 1, 1, 1)
        self.horizontalSlider_dilation_size = QtWidgets.QSlider(self.tab_mask)
        self.horizontalSlider_dilation_size.setMinimum(1)
        self.horizontalSlider_dilation_size.setMaximum(100)
        self.horizontalSlider_dilation_size.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_dilation_size.setObjectName("horizontalSlider_dilation_size")
        self.gridLayout_3.addWidget(self.horizontalSlider_dilation_size, 9, 1, 1, 1)
        self.p_max_area = QtWidgets.QSpinBox(self.tab_mask)
        self.p_max_area.setFrame(True)
        self.p_max_area.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.p_max_area.setAccelerated(False)
        self.p_max_area.setKeyboardTracking(True)
        self.p_max_area.setMinimum(10)
        self.p_max_area.setMaximum(100000000)
        self.p_max_area.setProperty("value", 5000)
        self.p_max_area.setProperty("showGroupSeparator", False)
        self.p_max_area.setObjectName("p_max_area")
        self.gridLayout_3.addWidget(self.p_max_area, 2, 2, 1, 1)
        self.p_min_area = QtWidgets.QSpinBox(self.tab_mask)
        self.p_min_area.setEnabled(False)
        self.p_min_area.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.p_min_area.setMaximum(100000000)
        self.p_min_area.setProperty("value", 100)
        self.p_min_area.setObjectName("p_min_area")
        self.gridLayout_3.addWidget(self.p_min_area, 2, 1, 1, 1)
        self.horizontalSlider_block_size = QtWidgets.QSlider(self.tab_mask)
        self.horizontalSlider_block_size.setMaximum(500)
        self.horizontalSlider_block_size.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_block_size.setObjectName("horizontalSlider_block_size")
        self.gridLayout_3.addWidget(self.horizontalSlider_block_size, 5, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(11, 11, 11, 11)
        self.formLayout.setSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.p_buff_size = QtWidgets.QSpinBox(self.tab_mask)
        self.p_buff_size.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.p_buff_size.setMinimum(1)
        self.p_buff_size.setMaximum(1000)
        self.p_buff_size.setProperty("value", 25)
        self.p_buff_size.setObjectName("p_buff_size")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.p_buff_size)
        self.label_5 = QtWidgets.QLabel(self.tab_mask)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_5)
        self.p_fps = QtWidgets.QDoubleSpinBox(self.tab_mask)
        self.p_fps.setProperty("value", 25.0)
        self.p_fps.setObjectName("p_fps")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.p_fps)
        self.label_fps = QtWidgets.QLabel(self.tab_mask)
        self.label_fps.setObjectName("label_fps")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_fps)
        self.p_keep_border_data = QtWidgets.QCheckBox(self.tab_mask)
        self.p_keep_border_data.setObjectName("p_keep_border_data")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.p_keep_border_data)
        self.p_is_light_background = QtWidgets.QCheckBox(self.tab_mask)
        self.p_is_light_background.setChecked(True)
        self.p_is_light_background.setObjectName("p_is_light_background")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.p_is_light_background)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.pushButton_moreParams = QtWidgets.QPushButton(self.tab_mask)
        self.pushButton_moreParams.setObjectName("pushButton_moreParams")
        self.verticalLayout_2.addWidget(self.pushButton_moreParams)
        self.pushButton_saveParam = QtWidgets.QPushButton(self.tab_mask)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_saveParam.sizePolicy().hasHeightForWidth())
        self.pushButton_saveParam.setSizePolicy(sizePolicy)
        self.pushButton_saveParam.setObjectName("pushButton_saveParam")
        self.verticalLayout_2.addWidget(self.pushButton_saveParam)
        self.tabWidget.addTab(self.tab_mask, "")
        self.tab_bgnd = QtWidgets.QWidget()
        self.tab_bgnd.setObjectName("tab_bgnd")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_bgnd)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.checkBox_is_bgnd_subtraction = QtWidgets.QCheckBox(self.tab_bgnd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_is_bgnd_subtraction.sizePolicy().hasHeightForWidth())
        self.checkBox_is_bgnd_subtraction.setSizePolicy(sizePolicy)
        self.checkBox_is_bgnd_subtraction.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_is_bgnd_subtraction.setObjectName("checkBox_is_bgnd_subtraction")
        self.verticalLayout_3.addWidget(self.checkBox_is_bgnd_subtraction)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label = QtWidgets.QLabel(self.tab_bgnd)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.p_mask_bgnd_buff_size = QtWidgets.QSpinBox(self.tab_bgnd)
        self.p_mask_bgnd_buff_size.setMinimum(1)
        self.p_mask_bgnd_buff_size.setMaximum(200)
        self.p_mask_bgnd_buff_size.setProperty("value", 25)
        self.p_mask_bgnd_buff_size.setObjectName("p_mask_bgnd_buff_size")
        self.gridLayout_4.addWidget(self.p_mask_bgnd_buff_size, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_bgnd)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 2, 0, 1, 1)
        self.p_mask_bgnd_frame_gap = QtWidgets.QSpinBox(self.tab_bgnd)
        self.p_mask_bgnd_frame_gap.setMinimum(1)
        self.p_mask_bgnd_frame_gap.setMaximum(1000000)
        self.p_mask_bgnd_frame_gap.setProperty("value", 250)
        self.p_mask_bgnd_frame_gap.setObjectName("p_mask_bgnd_frame_gap")
        self.gridLayout_4.addWidget(self.p_mask_bgnd_frame_gap, 3, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_4)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.tabWidget.addTab(self.tab_bgnd, "")
        self.tab_analysis = QtWidgets.QWidget()
        self.tab_analysis.setEnabled(True)
        self.tab_analysis.setObjectName("tab_analysis")
        self.radioButton_analysisType_worm = QtWidgets.QRadioButton(self.tab_analysis)
        self.radioButton_analysisType_worm.setGeometry(QtCore.QRect(10, 37, 100, 20))
        self.radioButton_analysisType_worm.setChecked(True)
        self.radioButton_analysisType_worm.setObjectName("radioButton_analysisType_worm")
        self.buttonGroup_analysisType = QtWidgets.QButtonGroup(GetMaskParams)
        self.buttonGroup_analysisType.setObjectName("buttonGroup_analysisType")
        self.buttonGroup_analysisType.addButton(self.radioButton_analysisType_worm)
        self.radioButton_analysisType_zebrafish = QtWidgets.QRadioButton(self.tab_analysis)
        self.radioButton_analysisType_zebrafish.setGeometry(QtCore.QRect(10, 60, 100, 20))
        self.radioButton_analysisType_zebrafish.setObjectName("radioButton_analysisType_zebrafish")
        self.buttonGroup_analysisType.addButton(self.radioButton_analysisType_zebrafish)
        self.label_7 = QtWidgets.QLabel(self.tab_analysis)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 121, 16))
        self.label_7.setStyleSheet("font-weight: bold;")
        self.label_7.setObjectName("label_7")
        self.groupBox_zebrafishOptions = QtWidgets.QGroupBox(self.tab_analysis)
        self.groupBox_zebrafishOptions.setGeometry(QtCore.QRect(0, 120, 231, 591))
        self.groupBox_zebrafishOptions.setObjectName("groupBox_zebrafishOptions")
        self.spinBox_zf_tailLength = QtWidgets.QSpinBox(self.groupBox_zebrafishOptions)
        self.spinBox_zf_tailLength.setEnabled(False)
        self.spinBox_zf_tailLength.setGeometry(QtCore.QRect(169, 152, 51, 24))
        self.spinBox_zf_tailLength.setMaximum(500)
        self.spinBox_zf_tailLength.setProperty("value", 60)
        self.spinBox_zf_tailLength.setObjectName("spinBox_zf_tailLength")
        self.label_zf_tailLength = QtWidgets.QLabel(self.groupBox_zebrafishOptions)
        self.label_zf_tailLength.setEnabled(False)
        self.label_zf_tailLength.setGeometry(QtCore.QRect(9, 152, 121, 16))
        self.label_zf_tailLength.setObjectName("label_zf_tailLength")
        self.spinBox_zf_minAngle = QtWidgets.QSpinBox(self.groupBox_zebrafishOptions)
        self.spinBox_zf_minAngle.setGeometry(QtCore.QRect(168, 29, 51, 24))
        self.spinBox_zf_minAngle.setMinimum(-180)
        self.spinBox_zf_minAngle.setMaximum(180)
        self.spinBox_zf_minAngle.setProperty("value", -90)
        self.spinBox_zf_minAngle.setObjectName("spinBox_zf_minAngle")
        self.label_10 = QtWidgets.QLabel(self.groupBox_zebrafishOptions)
        self.label_10.setGeometry(QtCore.QRect(8, 59, 121, 16))
        self.label_10.setObjectName("label_10")
        self.spinBox_zf_maxAngle = QtWidgets.QSpinBox(self.groupBox_zebrafishOptions)
        self.spinBox_zf_maxAngle.setGeometry(QtCore.QRect(168, 59, 51, 24))
        self.spinBox_zf_maxAngle.setMinimum(-90)
        self.spinBox_zf_maxAngle.setMaximum(90)
        self.spinBox_zf_maxAngle.setProperty("value", 90)
        self.spinBox_zf_maxAngle.setObjectName("spinBox_zf_maxAngle")
        self.label_9 = QtWidgets.QLabel(self.groupBox_zebrafishOptions)
        self.label_9.setGeometry(QtCore.QRect(8, 29, 121, 16))
        self.label_9.setObjectName("label_9")
        self.spinBox_zf_numberOfSegments = QtWidgets.QSpinBox(self.groupBox_zebrafishOptions)
        self.spinBox_zf_numberOfSegments.setEnabled(False)
        self.spinBox_zf_numberOfSegments.setGeometry(QtCore.QRect(169, 182, 51, 24))
        self.spinBox_zf_numberOfSegments.setMinimum(1)
        self.spinBox_zf_numberOfSegments.setProperty("value", 12)
        self.spinBox_zf_numberOfSegments.setObjectName("spinBox_zf_numberOfSegments")
        self.label_11 = QtWidgets.QLabel(self.groupBox_zebrafishOptions)
        self.label_11.setGeometry(QtCore.QRect(8, 89, 121, 16))
        self.label_11.setObjectName("label_11")
        self.label_zf_numberOfSegments = QtWidgets.QLabel(self.groupBox_zebrafishOptions)
        self.label_zf_numberOfSegments.setEnabled(False)
        self.label_zf_numberOfSegments.setGeometry(QtCore.QRect(9, 182, 131, 16))
        self.label_zf_numberOfSegments.setObjectName("label_zf_numberOfSegments")
        self.spinBox_zf_anglesPerSegment = QtWidgets.QSpinBox(self.groupBox_zebrafishOptions)
        self.spinBox_zf_anglesPerSegment.setGeometry(QtCore.QRect(168, 89, 51, 24))
        self.spinBox_zf_anglesPerSegment.setMaximum(180)
        self.spinBox_zf_anglesPerSegment.setProperty("value", 180)
        self.spinBox_zf_anglesPerSegment.setObjectName("spinBox_zf_anglesPerSegment")
        self.spinBox_zf_segmentDrawWidth = QtWidgets.QSpinBox(self.groupBox_zebrafishOptions)
        self.spinBox_zf_segmentDrawWidth.setGeometry(QtCore.QRect(169, 242, 51, 24))
        self.spinBox_zf_segmentDrawWidth.setMinimum(1)
        self.spinBox_zf_segmentDrawWidth.setProperty("value", 2)
        self.spinBox_zf_segmentDrawWidth.setObjectName("spinBox_zf_segmentDrawWidth")
        self.label_14 = QtWidgets.QLabel(self.groupBox_zebrafishOptions)
        self.label_14.setGeometry(QtCore.QRect(9, 284, 191, 16))
        self.label_14.setObjectName("label_14")
        self.spinBox_zf_segmentTestWidth = QtWidgets.QSpinBox(self.groupBox_zebrafishOptions)
        self.spinBox_zf_segmentTestWidth.setEnabled(False)
        self.spinBox_zf_segmentTestWidth.setGeometry(QtCore.QRect(169, 212, 51, 24))
        self.spinBox_zf_segmentTestWidth.setMinimum(1)
        self.spinBox_zf_segmentTestWidth.setProperty("value", 2)
        self.spinBox_zf_segmentTestWidth.setObjectName("spinBox_zf_segmentTestWidth")
        self.label_15 = QtWidgets.QLabel(self.groupBox_zebrafishOptions)
        self.label_15.setGeometry(QtCore.QRect(9, 362, 141, 16))
        self.label_15.setObjectName("label_15")
        self.label_zf_segmentDrawWidth = QtWidgets.QLabel(self.groupBox_zebrafishOptions)
        self.label_zf_segmentDrawWidth.setGeometry(QtCore.QRect(9, 246, 151, 16))
        self.label_zf_segmentDrawWidth.setObjectName("label_zf_segmentDrawWidth")
        self.label_zf_segmentTestWidth = QtWidgets.QLabel(self.groupBox_zebrafishOptions)
        self.label_zf_segmentTestWidth.setEnabled(False)
        self.label_zf_segmentTestWidth.setGeometry(QtCore.QRect(9, 215, 141, 16))
        self.label_zf_segmentTestWidth.setObjectName("label_zf_segmentTestWidth")
        self.radioButton_zf_tailDetection_modelEndPoint = QtWidgets.QRadioButton(self.groupBox_zebrafishOptions)
        self.radioButton_zf_tailDetection_modelEndPoint.setGeometry(QtCore.QRect(29, 304, 141, 20))
        self.radioButton_zf_tailDetection_modelEndPoint.setChecked(True)
        self.radioButton_zf_tailDetection_modelEndPoint.setObjectName("radioButton_zf_tailDetection_modelEndPoint")
        self.buttonGroup_zf_tailPointDetectionAlgorithm = QtWidgets.QButtonGroup(GetMaskParams)
        self.buttonGroup_zf_tailPointDetectionAlgorithm.setObjectName("buttonGroup_zf_tailPointDetectionAlgorithm")
        self.buttonGroup_zf_tailPointDetectionAlgorithm.addButton(self.radioButton_zf_tailDetection_modelEndPoint)
        self.radioButton_zf_tailDetection_maximumCurvature = QtWidgets.QRadioButton(self.groupBox_zebrafishOptions)
        self.radioButton_zf_tailDetection_maximumCurvature.setGeometry(QtCore.QRect(29, 326, 151, 20))
        self.radioButton_zf_tailDetection_maximumCurvature.setObjectName("radioButton_zf_tailDetection_maximumCurvature")
        self.buttonGroup_zf_tailPointDetectionAlgorithm.addButton(self.radioButton_zf_tailDetection_maximumCurvature)
        self.spinBox_zf_pruneRetention = QtWidgets.QSpinBox(self.groupBox_zebrafishOptions)
        self.spinBox_zf_pruneRetention.setGeometry(QtCore.QRect(169, 359, 51, 24))
        self.spinBox_zf_pruneRetention.setMinimum(1)
        self.spinBox_zf_pruneRetention.setMaximum(1000)
        self.spinBox_zf_pruneRetention.setProperty("value", 1)
        self.spinBox_zf_pruneRetention.setObjectName("spinBox_zf_pruneRetention")
        self.checkBox_autoDetectTailLength = QtWidgets.QCheckBox(self.groupBox_zebrafishOptions)
        self.checkBox_autoDetectTailLength.setGeometry(QtCore.QRect(8, 120, 171, 20))
        self.checkBox_autoDetectTailLength.setChecked(True)
        self.checkBox_autoDetectTailLength.setObjectName("checkBox_autoDetectTailLength")
        self.tabWidget.addTab(self.tab_analysis, "")
        self.horizontalLayout_5.addWidget(self.tabWidget)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.graphicsView_full = QtWidgets.QGraphicsView(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView_full.sizePolicy().hasHeightForWidth())
        self.graphicsView_full.setSizePolicy(sizePolicy)
        self.graphicsView_full.setDragMode(QtWidgets.QGraphicsView.ScrollHandDrag)
        self.graphicsView_full.setTransformationAnchor(QtWidgets.QGraphicsView.AnchorUnderMouse)
        self.graphicsView_full.setResizeAnchor(QtWidgets.QGraphicsView.AnchorViewCenter)
        self.graphicsView_full.setObjectName("graphicsView_full")
        self.horizontalLayout_2.addWidget(self.graphicsView_full)
        self.graphicsView_mask = QtWidgets.QGraphicsView(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView_mask.sizePolicy().hasHeightForWidth())
        self.graphicsView_mask.setSizePolicy(sizePolicy)
        self.graphicsView_mask.setDragMode(QtWidgets.QGraphicsView.ScrollHandDrag)
        self.graphicsView_mask.setTransformationAnchor(QtWidgets.QGraphicsView.AnchorUnderMouse)
        self.graphicsView_mask.setResizeAnchor(QtWidgets.QGraphicsView.AnchorViewCenter)
        self.graphicsView_mask.setObjectName("graphicsView_mask")
        self.horizontalLayout_2.addWidget(self.graphicsView_mask)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.widget = QtWidgets.QWidget(self.centralWidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_paramFile = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_paramFile.sizePolicy().hasHeightForWidth())
        self.pushButton_paramFile.setSizePolicy(sizePolicy)
        self.pushButton_paramFile.setObjectName("pushButton_paramFile")
        self.gridLayout.addWidget(self.pushButton_paramFile, 1, 0, 1, 1)
        self.pushButton_video = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_video.sizePolicy().hasHeightForWidth())
        self.pushButton_video.setSizePolicy(sizePolicy)
        self.pushButton_video.setObjectName("pushButton_video")
        self.gridLayout.addWidget(self.pushButton_video, 0, 0, 1, 1)
        self.lineEdit_video = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_video.setObjectName("lineEdit_video")
        self.gridLayout.addWidget(self.lineEdit_video, 0, 1, 1, 1)
        self.lineEdit_paramFile = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_paramFile.setObjectName("lineEdit_paramFile")
        self.gridLayout.addWidget(self.lineEdit_paramFile, 1, 1, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_next = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_next.sizePolicy().hasHeightForWidth())
        self.pushButton_next.setSizePolicy(sizePolicy)
        self.pushButton_next.setObjectName("pushButton_next")
        self.gridLayout_2.addWidget(self.pushButton_next, 1, 1, 1, 1)
        self.spinBox_frame_number = QtWidgets.QSpinBox(self.widget)
        self.spinBox_frame_number.setEnabled(False)
        self.spinBox_frame_number.setAutoFillBackground(False)
        self.spinBox_frame_number.setWrapping(False)
        self.spinBox_frame_number.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_frame_number.setReadOnly(True)
        self.spinBox_frame_number.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_frame_number.setAccelerated(False)
        self.spinBox_frame_number.setMaximum(100000000)
        self.spinBox_frame_number.setProperty("showGroupSeparator", False)
        self.spinBox_frame_number.setObjectName("spinBox_frame_number")
        self.gridLayout_2.addWidget(self.spinBox_frame_number, 0, 1, 1, 1)
        self.pushButton_play = QtWidgets.QPushButton(self.widget)
        self.pushButton_play.setObjectName("pushButton_play")
        self.gridLayout_2.addWidget(self.pushButton_play, 0, 0, 2, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.horizontalLayout_4.addWidget(self.widget)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5.addLayout(self.verticalLayout_7)
        self.horizontalLayout_5.setStretch(1, 8)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        GetMaskParams.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(GetMaskParams)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 986, 22))
        self.menuBar.setObjectName("menuBar")
        GetMaskParams.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(GetMaskParams)
        self.mainToolBar.setObjectName("mainToolBar")
        GetMaskParams.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(GetMaskParams)
        self.statusBar.setObjectName("statusBar")
        GetMaskParams.setStatusBar(self.statusBar)

        self.retranslateUi(GetMaskParams)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(GetMaskParams)

    def retranslateUi(self, GetMaskParams):
        _translate = QtCore.QCoreApplication.translate
        GetMaskParams.setWindowTitle(_translate("GetMaskParams", "GetMaskParams"))
        self.label_thresh_C.setText(_translate("GetMaskParams", "Thresh_C"))
        self.label_6.setText(_translate("GetMaskParams", "Dilation"))
        self.label_max_aea.setText(_translate("GetMaskParams", "Max Area"))
        self.label_min_area.setText(_translate("GetMaskParams", "Min Area"))
        self.label_block_size.setText(_translate("GetMaskParams", "Block Size"))
        self.label_5.setText(_translate("GetMaskParams", "Frames to average"))
        self.label_fps.setText(_translate("GetMaskParams", "Expected FPS"))
        self.p_keep_border_data.setText(_translate("GetMaskParams", "keep border data?"))
        self.p_is_light_background.setText(_translate("GetMaskParams", "is light background?"))
        self.pushButton_moreParams.setText(_translate("GetMaskParams", "Edit more parameters"))
        self.pushButton_saveParam.setText(_translate("GetMaskParams", "Save Parameters"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_mask), _translate("GetMaskParams", "Mask"))
        self.checkBox_is_bgnd_subtraction.setText(_translate("GetMaskParams", "Subtract Background"))
        self.label.setText(_translate("GetMaskParams", "Background buffer size"))
        self.label_2.setText(_translate("GetMaskParams", "Gap between frames"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_bgnd), _translate("GetMaskParams", "Background"))
        self.radioButton_analysisType_worm.setText(_translate("GetMaskParams", "Worm"))
        self.radioButton_analysisType_zebrafish.setText(_translate("GetMaskParams", "Zebrafish"))
        self.label_7.setText(_translate("GetMaskParams", "Analysis Type"))
        self.groupBox_zebrafishOptions.setTitle(_translate("GetMaskParams", "Zebrafish Options"))
        self.label_zf_tailLength.setText(_translate("GetMaskParams", "Tail length"))
        self.label_10.setText(_translate("GetMaskParams", "Segment max angle"))
        self.label_9.setText(_translate("GetMaskParams", "Segment min angle"))
        self.label_11.setText(_translate("GetMaskParams", "Angles per segment"))
        self.label_zf_numberOfSegments.setText(_translate("GetMaskParams", "Number of segments"))
        self.label_14.setText(_translate("GetMaskParams", "Tail point detection algorithm"))
        self.label_15.setText(_translate("GetMaskParams", "Prune retention"))
        self.label_zf_segmentDrawWidth.setText(_translate("GetMaskParams", "Segment draw width"))
        self.label_zf_segmentTestWidth.setText(_translate("GetMaskParams", "Segment test width"))
        self.radioButton_zf_tailDetection_modelEndPoint.setText(_translate("GetMaskParams", "Model end point"))
        self.radioButton_zf_tailDetection_maximumCurvature.setText(_translate("GetMaskParams", "Maximum curvature"))
        self.checkBox_autoDetectTailLength.setText(_translate("GetMaskParams", "Auto-detect tail length"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_analysis), _translate("GetMaskParams", "Analysis"))
        self.pushButton_paramFile.setText(_translate("GetMaskParams", "Parameters File"))
        self.pushButton_video.setText(_translate("GetMaskParams", "Video File"))
        self.pushButton_next.setText(_translate("GetMaskParams", "Next Chunk"))
        self.pushButton_play.setText(_translate("GetMaskParams", "Play"))

