# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'imageviewer.ui'
#
# Created: Fri Jul 24 15:20:52 2015
#      by: PyQt5 UI code generator 5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ImageViewer(object):
    def setupUi(self, ImageViewer):
        ImageViewer.setObjectName("ImageViewer")
        ImageViewer.resize(936, 797)
        ImageViewer.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralWidget = QtWidgets.QWidget(ImageViewer)
        self.centralWidget.setEnabled(True)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.radioButton_ROI1 = QtWidgets.QRadioButton(self.centralWidget)
        self.radioButton_ROI1.setText("")
        self.radioButton_ROI1.setChecked(True)
        self.radioButton_ROI1.setObjectName("radioButton_ROI1")
        self.gridLayout_3.addWidget(self.radioButton_ROI1, 1, 2, 1, 1)
        self.radioButton_ROI2 = QtWidgets.QRadioButton(self.centralWidget)
        self.radioButton_ROI2.setText("")
        self.radioButton_ROI2.setObjectName("radioButton_ROI2")
        self.gridLayout_3.addWidget(self.radioButton_ROI2, 4, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(600, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 4, 1, 1, 1)
        self.wormCanvas1 = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wormCanvas1.sizePolicy().hasHeightForWidth())
        self.wormCanvas1.setSizePolicy(sizePolicy)
        self.wormCanvas1.setFrameShape(QtWidgets.QFrame.Box)
        self.wormCanvas1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.wormCanvas1.setText("")
        self.wormCanvas1.setObjectName("wormCanvas1")
        self.gridLayout_3.addWidget(self.wormCanvas1, 0, 2, 1, 3)
        self.wormCanvas2 = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wormCanvas2.sizePolicy().hasHeightForWidth())
        self.wormCanvas2.setSizePolicy(sizePolicy)
        self.wormCanvas2.setFrameShape(QtWidgets.QFrame.Box)
        self.wormCanvas2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.wormCanvas2.setText("")
        self.wormCanvas2.setObjectName("wormCanvas2")
        self.gridLayout_3.addWidget(self.wormCanvas2, 2, 2, 1, 3)
        self.comboBox_ROI1 = QtWidgets.QComboBox(self.centralWidget)
        self.comboBox_ROI1.setObjectName("comboBox_ROI1")
        self.gridLayout_3.addWidget(self.comboBox_ROI1, 1, 3, 1, 1)
        self.checkBox_ROI1 = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_ROI1.setChecked(True)
        self.checkBox_ROI1.setObjectName("checkBox_ROI1")
        self.gridLayout_3.addWidget(self.checkBox_ROI1, 1, 4, 1, 1)
        self.comboBox_ROI2 = QtWidgets.QComboBox(self.centralWidget)
        self.comboBox_ROI2.setObjectName("comboBox_ROI2")
        self.gridLayout_3.addWidget(self.comboBox_ROI2, 4, 3, 1, 1)
        self.checkBox_ROI2 = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_ROI2.setChecked(True)
        self.checkBox_ROI2.setObjectName("checkBox_ROI2")
        self.gridLayout_3.addWidget(self.checkBox_ROI2, 4, 4, 1, 1)
        self.checkBox_label = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_label.setChecked(True)
        self.checkBox_label.setObjectName("checkBox_label")
        self.gridLayout_3.addWidget(self.checkBox_label, 4, 0, 1, 1)
        self.imageCanvas = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageCanvas.sizePolicy().hasHeightForWidth())
        self.imageCanvas.setSizePolicy(sizePolicy)
        self.imageCanvas.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.imageCanvas.setFrameShape(QtWidgets.QFrame.Box)
        self.imageCanvas.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.imageCanvas.setText("")
        self.imageCanvas.setObjectName("imageCanvas")
        self.gridLayout_3.addWidget(self.imageCanvas, 0, 0, 3, 2)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem1, 0, 2, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.spinBox_frame = QtWidgets.QSpinBox(self.centralWidget)
        self.spinBox_frame.setObjectName("spinBox_frame")
        self.gridLayout.addWidget(self.spinBox_frame, 0, 1, 1, 1)
        self.label_frame = QtWidgets.QLabel(self.centralWidget)
        self.label_frame.setAlignment(QtCore.Qt.AlignCenter)
        self.label_frame.setObjectName("label_frame")
        self.gridLayout.addWidget(self.label_frame, 0, 0, 1, 1)
        self.pushButton_video = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_video.setObjectName("pushButton_video")
        self.gridLayout.addWidget(self.pushButton_video, 3, 0, 1, 2)
        self.pushButton_skel = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_skel.setObjectName("pushButton_skel")
        self.gridLayout.addWidget(self.pushButton_skel, 4, 0, 1, 2)
        self.label_fps = QtWidgets.QLabel(self.centralWidget)
        self.label_fps.setAlignment(QtCore.Qt.AlignCenter)
        self.label_fps.setObjectName("label_fps")
        self.gridLayout.addWidget(self.label_fps, 2, 0, 1, 1)
        self.label_step = QtWidgets.QLabel(self.centralWidget)
        self.label_step.setAlignment(QtCore.Qt.AlignCenter)
        self.label_step.setObjectName("label_step")
        self.gridLayout.addWidget(self.label_step, 1, 0, 1, 1)
        self.doubleSpinBox_fps = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.doubleSpinBox_fps.setMaximum(100.0)
        self.doubleSpinBox_fps.setProperty("value", 25.0)
        self.doubleSpinBox_fps.setObjectName("doubleSpinBox_fps")
        self.gridLayout.addWidget(self.doubleSpinBox_fps, 2, 1, 1, 1)
        self.spinBox_step = QtWidgets.QSpinBox(self.centralWidget)
        self.spinBox_step.setMaximum(100000)
        self.spinBox_step.setProperty("value", 1)
        self.spinBox_step.setObjectName("spinBox_step")
        self.gridLayout.addWidget(self.spinBox_step, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 5, 0, 1, 2)
        self.lineEdit_video = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_video.setText("")
        self.lineEdit_video.setObjectName("lineEdit_video")
        self.gridLayout.addWidget(self.lineEdit_video, 3, 3, 1, 2)
        self.lineEdit_skel = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_skel.setObjectName("lineEdit_skel")
        self.gridLayout.addWidget(self.lineEdit_skel, 4, 3, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 3, 1, 1)
        self.playButton = QtWidgets.QPushButton(self.centralWidget)
        self.playButton.setCheckable(False)
        self.playButton.setObjectName("playButton")
        self.gridLayout.addWidget(self.playButton, 1, 4, 1, 1)
        self.imageSlider = QtWidgets.QSlider(self.centralWidget)
        self.imageSlider.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.imageSlider.setMouseTracking(True)
        self.imageSlider.setAutoFillBackground(False)
        self.imageSlider.setMaximum(100)
        self.imageSlider.setOrientation(QtCore.Qt.Horizontal)
        self.imageSlider.setInvertedAppearance(False)
        self.imageSlider.setInvertedControls(False)
        self.imageSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.imageSlider.setObjectName("imageSlider")
        self.gridLayout.addWidget(self.imageSlider, 0, 3, 1, 2)
        self.comboBox_h5path = QtWidgets.QComboBox(self.centralWidget)
        self.comboBox_h5path.setEditable(True)
        self.comboBox_h5path.setObjectName("comboBox_h5path")
        self.comboBox_h5path.addItem("")
        self.comboBox_h5path.addItem("")
        self.gridLayout.addWidget(self.comboBox_h5path, 5, 3, 1, 2)
        self.gridLayout_4.addLayout(self.gridLayout, 1, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 0, 0, 1, 1)
        ImageViewer.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(ImageViewer)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 936, 22))
        self.menuBar.setObjectName("menuBar")
        ImageViewer.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(ImageViewer)
        self.mainToolBar.setObjectName("mainToolBar")
        ImageViewer.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.toolBar = QtWidgets.QToolBar(ImageViewer)
        self.toolBar.setObjectName("toolBar")
        ImageViewer.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(ImageViewer)
        QtCore.QMetaObject.connectSlotsByName(ImageViewer)

    def retranslateUi(self, ImageViewer):
        _translate = QtCore.QCoreApplication.translate
        ImageViewer.setWindowTitle(_translate("ImageViewer", "ImageViewer"))
        self.checkBox_ROI1.setText(_translate("ImageViewer", "Show skeletons"))
        self.checkBox_ROI2.setText(_translate("ImageViewer", "Show skeletons"))
        self.checkBox_label.setText(_translate("ImageViewer", "Show labels"))
        self.label_frame.setText(_translate("ImageViewer", "Frame"))
        self.pushButton_video.setText(_translate("ImageViewer", "Select Video File"))
        self.pushButton_skel.setText(_translate("ImageViewer", "Select Skeletons File"))
        self.label_fps.setText(_translate("ImageViewer", "FPS display"))
        self.label_step.setText(_translate("ImageViewer", "Step Size"))
        self.label.setText(_translate("ImageViewer", "HDF5 video group"))
        self.playButton.setText(_translate("ImageViewer", "Play"))
        self.comboBox_h5path.setItemText(0, _translate("ImageViewer", "/mask"))
        self.comboBox_h5path.setItemText(1, _translate("ImageViewer", "/full_data"))
        self.toolBar.setWindowTitle(_translate("ImageViewer", "toolBar"))

