# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1161, 746)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.spinBox_thresh_C = QtWidgets.QSpinBox(self.centralWidget)
        self.spinBox_thresh_C.setMinimum(-100)
        self.spinBox_thresh_C.setMaximum(100)
        self.spinBox_thresh_C.setProperty("value", 15)
        self.spinBox_thresh_C.setObjectName("spinBox_thresh_C")
        self.verticalLayout_4.addWidget(self.spinBox_thresh_C)
        self.gridLayout.addLayout(self.verticalLayout_4, 3, 0, 1, 1)
        self.lineEdit_results = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_results.setObjectName("lineEdit_results")
        self.gridLayout.addWidget(self.lineEdit_results, 18, 3, 1, 2)
        self.dial_min_area = QtWidgets.QDial(self.centralWidget)
        self.dial_min_area.setMaximum(10000)
        self.dial_min_area.setProperty("value", 100)
        self.dial_min_area.setObjectName("dial_min_area")
        self.gridLayout.addWidget(self.dial_min_area, 0, 1, 1, 1)
        self.dial_max_area = QtWidgets.QDial(self.centralWidget)
        self.dial_max_area.setMinimum(100)
        self.dial_max_area.setMaximum(100000)
        self.dial_max_area.setProperty("value", 5000)
        self.dial_max_area.setObjectName("dial_max_area")
        self.gridLayout.addWidget(self.dial_max_area, 1, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.spinBox_min_area = QtWidgets.QSpinBox(self.centralWidget)
        self.spinBox_min_area.setMaximum(10000000)
        self.spinBox_min_area.setProperty("value", 100)
        self.spinBox_min_area.setObjectName("spinBox_min_area")
        self.verticalLayout.addWidget(self.spinBox_min_area)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.dial_thresh_C = QtWidgets.QDial(self.centralWidget)
        self.dial_thresh_C.setMinimum(5)
        self.dial_thresh_C.setMaximum(100)
        self.dial_thresh_C.setProperty("value", 15)
        self.dial_thresh_C.setObjectName("dial_thresh_C")
        self.gridLayout.addWidget(self.dial_thresh_C, 3, 1, 1, 1)
        self.dial_block_size = QtWidgets.QDial(self.centralWidget)
        self.dial_block_size.setMinimum(5)
        self.dial_block_size.setMaximum(200)
        self.dial_block_size.setProperty("value", 61)
        self.dial_block_size.setObjectName("dial_block_size")
        self.gridLayout.addWidget(self.dial_block_size, 6, 1, 1, 1)
        self.pushButton_mask = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_mask.setObjectName("pushButton_mask")
        self.gridLayout.addWidget(self.pushButton_mask, 19, 2, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.spinBox_block_size = QtWidgets.QSpinBox(self.centralWidget)
        self.spinBox_block_size.setMinimum(5)
        self.spinBox_block_size.setMaximum(1000000)
        self.spinBox_block_size.setProperty("value", 61)
        self.spinBox_block_size.setObjectName("spinBox_block_size")
        self.verticalLayout_3.addWidget(self.spinBox_block_size)
        self.gridLayout.addLayout(self.verticalLayout_3, 6, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.spinBox_max_area = QtWidgets.QSpinBox(self.centralWidget)
        self.spinBox_max_area.setMinimum(100)
        self.spinBox_max_area.setMaximum(10000000)
        self.spinBox_max_area.setProperty("value", 5000)
        self.spinBox_max_area.setObjectName("spinBox_max_area")
        self.verticalLayout_2.addWidget(self.spinBox_max_area)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.pushButton_start = QtWidgets.QPushButton(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButton_start.setFont(font)
        self.pushButton_start.setMouseTracking(False)
        self.pushButton_start.setAutoFillBackground(False)
        self.pushButton_start.setCheckable(False)
        self.pushButton_start.setObjectName("pushButton_start")
        self.gridLayout.addWidget(self.pushButton_start, 19, 0, 1, 2)
        self.pushButton_video = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_video.setObjectName("pushButton_video")
        self.gridLayout.addWidget(self.pushButton_video, 17, 2, 1, 1)
        self.pushButton_results = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_results.setObjectName("pushButton_results")
        self.gridLayout.addWidget(self.pushButton_results, 18, 2, 1, 1)
        self.lineEdit_mask = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_mask.setReadOnly(True)
        self.lineEdit_mask.setObjectName("lineEdit_mask")
        self.gridLayout.addWidget(self.lineEdit_mask, 19, 3, 1, 2)
        self.lineEdit_video = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_video.setObjectName("lineEdit_video")
        self.gridLayout.addWidget(self.lineEdit_video, 17, 3, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 16, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 16, 3, 1, 1)
        self.pushButton_next = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_next.sizePolicy().hasHeightForWidth())
        self.pushButton_next.setSizePolicy(sizePolicy)
        self.pushButton_next.setObjectName("pushButton_next")
        self.gridLayout.addWidget(self.pushButton_next, 16, 5, 1, 1)
        self.label_mask = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_mask.sizePolicy().hasHeightForWidth())
        self.label_mask.setSizePolicy(sizePolicy)
        self.label_mask.setFrameShape(QtWidgets.QFrame.Box)
        self.label_mask.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_mask.setText("")
        self.label_mask.setObjectName("label_mask")
        self.gridLayout.addWidget(self.label_mask, 0, 4, 13, 2)
        self.label_full = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_full.sizePolicy().hasHeightForWidth())
        self.label_full.setSizePolicy(sizePolicy)
        self.label_full.setFrameShape(QtWidgets.QFrame.Box)
        self.label_full.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_full.setText("")
        self.label_full.setWordWrap(False)
        self.label_full.setObjectName("label_full")
        self.gridLayout.addWidget(self.label_full, 0, 2, 13, 2)
        self.checkBox_hasTimestamp = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_hasTimestamp.setChecked(True)
        self.checkBox_hasTimestamp.setObjectName("checkBox_hasTimestamp")
        self.gridLayout.addWidget(self.checkBox_hasTimestamp, 9, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_6 = QtWidgets.QLabel(self.centralWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_skelSeg = QtWidgets.QLabel(self.centralWidget)
        self.label_skelSeg.setObjectName("label_skelSeg")
        self.gridLayout_3.addWidget(self.label_skelSeg, 1, 0, 1, 1)
        self.spinBox_fps = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.spinBox_fps.setProperty("value", 25.0)
        self.spinBox_fps.setObjectName("spinBox_fps")
        self.gridLayout_3.addWidget(self.spinBox_fps, 2, 1, 1, 1)
        self.label_fps = QtWidgets.QLabel(self.centralWidget)
        self.label_fps.setObjectName("label_fps")
        self.gridLayout_3.addWidget(self.label_fps, 2, 0, 1, 1)
        self.spinBox_buff_size = QtWidgets.QSpinBox(self.centralWidget)
        self.spinBox_buff_size.setMinimum(1)
        self.spinBox_buff_size.setMaximum(1000)
        self.spinBox_buff_size.setProperty("value", 25)
        self.spinBox_buff_size.setObjectName("spinBox_buff_size")
        self.gridLayout_3.addWidget(self.spinBox_buff_size, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 3, 0, 1, 1)
        self.spinBox_skelSeg = QtWidgets.QSpinBox(self.centralWidget)
        self.spinBox_skelSeg.setProperty("value", 49)
        self.spinBox_skelSeg.setObjectName("spinBox_skelSeg")
        self.gridLayout_3.addWidget(self.spinBox_skelSeg, 1, 1, 1, 1)
        self.spinBox_dilation_size = QtWidgets.QSpinBox(self.centralWidget)
        self.spinBox_dilation_size.setMinimum(1)
        self.spinBox_dilation_size.setMaximum(999)
        self.spinBox_dilation_size.setProperty("value", 9)
        self.spinBox_dilation_size.setObjectName("spinBox_dilation_size")
        self.gridLayout_3.addWidget(self.spinBox_dilation_size, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 15, 0, 4, 2)
        self.checkBox_keepBorderData = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_keepBorderData.setObjectName("checkBox_keepBorderData")
        self.gridLayout.addWidget(self.checkBox_keepBorderData, 9, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1161, 22))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Thresh_C"))
        self.label.setText(_translate("MainWindow", "Min Area"))
        self.pushButton_mask.setText(_translate("MainWindow", "Mask Dir"))
        self.label_3.setText(_translate("MainWindow", "Block Size"))
        self.label_4.setText(_translate("MainWindow", "Max Area"))
        self.pushButton_start.setText(_translate("MainWindow", "Start"))
        self.pushButton_video.setText(_translate("MainWindow", "Video File"))
        self.pushButton_results.setText(_translate("MainWindow", "Results Dir"))
        self.pushButton_next.setText(_translate("MainWindow", "Next Chunk"))
        self.checkBox_hasTimestamp.setText(_translate("MainWindow", "has time stamp?"))
        self.label_6.setText(_translate("MainWindow", "Dilation"))
        self.label_skelSeg.setText(_translate("MainWindow", "Skeleton Segments"))
        self.label_fps.setText(_translate("MainWindow", "FPS"))
        self.label_5.setText(_translate("MainWindow", "Frames to average"))
        self.checkBox_keepBorderData.setText(_translate("MainWindow", "keep border data?"))

