# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Tue Jul 28 11:41:00 2015
#      by: PyQt5 UI code generator 5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(727, 746)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 6, 4, 1, 1)
        self.pushButton_results = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_results.setObjectName("pushButton_results")
        self.gridLayout.addWidget(self.pushButton_results, 8, 0, 1, 1)
        self.lineEdit_results = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_results.setObjectName("lineEdit_results")
        self.gridLayout.addWidget(self.lineEdit_results, 8, 1, 1, 4)
        self.lineEdit_mask = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_mask.setReadOnly(True)
        self.lineEdit_mask.setObjectName("lineEdit_mask")
        self.gridLayout.addWidget(self.lineEdit_mask, 9, 1, 1, 4)
        self.lineEdit_video = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_video.setObjectName("lineEdit_video")
        self.gridLayout.addWidget(self.lineEdit_video, 7, 1, 1, 4)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 6, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.dial_max_area = QtWidgets.QDial(self.centralWidget)
        self.dial_max_area.setMinimum(500)
        self.dial_max_area.setMaximum(10000)
        self.dial_max_area.setProperty("value", 5000)
        self.dial_max_area.setObjectName("dial_max_area")
        self.verticalLayout_2.addWidget(self.dial_max_area)
        self.spinBox_max_area = QtWidgets.QSpinBox(self.centralWidget)
        self.spinBox_max_area.setMinimum(500)
        self.spinBox_max_area.setMaximum(10000)
        self.spinBox_max_area.setProperty("value", 5000)
        self.spinBox_max_area.setObjectName("spinBox_max_area")
        self.verticalLayout_2.addWidget(self.spinBox_max_area)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.dial_thresh_C = QtWidgets.QDial(self.centralWidget)
        self.dial_thresh_C.setMinimum(5)
        self.dial_thresh_C.setMaximum(100)
        self.dial_thresh_C.setProperty("value", 15)
        self.dial_thresh_C.setObjectName("dial_thresh_C")
        self.verticalLayout_4.addWidget(self.dial_thresh_C)
        self.spinBox_thresh_C = QtWidgets.QSpinBox(self.centralWidget)
        self.spinBox_thresh_C.setMinimum(-100)
        self.spinBox_thresh_C.setMaximum(100)
        self.spinBox_thresh_C.setProperty("value", 15)
        self.spinBox_thresh_C.setObjectName("spinBox_thresh_C")
        self.verticalLayout_4.addWidget(self.spinBox_thresh_C)
        self.gridLayout.addLayout(self.verticalLayout_4, 3, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.dial_block_size = QtWidgets.QDial(self.centralWidget)
        self.dial_block_size.setMinimum(5)
        self.dial_block_size.setMaximum(200)
        self.dial_block_size.setProperty("value", 61)
        self.dial_block_size.setObjectName("dial_block_size")
        self.verticalLayout_3.addWidget(self.dial_block_size)
        self.spinBox_block_size = QtWidgets.QSpinBox(self.centralWidget)
        self.spinBox_block_size.setMinimum(5)
        self.spinBox_block_size.setMaximum(200)
        self.spinBox_block_size.setProperty("value", 61)
        self.spinBox_block_size.setObjectName("spinBox_block_size")
        self.verticalLayout_3.addWidget(self.spinBox_block_size)
        self.gridLayout.addLayout(self.verticalLayout_3, 4, 0, 1, 1)
        self.pushButton_video = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_video.setObjectName("pushButton_video")
        self.gridLayout.addWidget(self.pushButton_video, 7, 0, 1, 1)
        self.pushButton_mask = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_mask.setObjectName("pushButton_mask")
        self.gridLayout.addWidget(self.pushButton_mask, 9, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.dial_min_area = QtWidgets.QDial(self.centralWidget)
        self.dial_min_area.setMaximum(1000)
        self.dial_min_area.setProperty("value", 100)
        self.dial_min_area.setObjectName("dial_min_area")
        self.verticalLayout.addWidget(self.dial_min_area)
        self.spinBox_min_area = QtWidgets.QSpinBox(self.centralWidget)
        self.spinBox_min_area.setMaximum(1000)
        self.spinBox_min_area.setProperty("value", 100)
        self.spinBox_min_area.setObjectName("spinBox_min_area")
        self.verticalLayout.addWidget(self.spinBox_min_area)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.label_full = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_full.sizePolicy().hasHeightForWidth())
        self.label_full.setSizePolicy(sizePolicy)
        self.label_full.setFrameShape(QtWidgets.QFrame.Box)
        self.label_full.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_full.setText("")
        self.label_full.setWordWrap(False)
        self.label_full.setObjectName("label_full")
        self.gridLayout.addWidget(self.label_full, 0, 1, 6, 2)
        self.label_mask = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_mask.sizePolicy().hasHeightForWidth())
        self.label_mask.setSizePolicy(sizePolicy)
        self.label_mask.setFrameShape(QtWidgets.QFrame.Box)
        self.label_mask.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_mask.setText("")
        self.label_mask.setObjectName("label_mask")
        self.gridLayout.addWidget(self.label_mask, 0, 3, 6, 2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 6, 0, 1, 1)
        self.pushButton_start = QtWidgets.QPushButton(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButton_start.setFont(font)
        self.pushButton_start.setMouseTracking(False)
        self.pushButton_start.setAutoFillBackground(False)
        self.pushButton_start.setCheckable(False)
        self.pushButton_start.setObjectName("pushButton_start")
        self.gridLayout.addWidget(self.pushButton_start, 5, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 727, 22))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_results.setText(_translate("MainWindow", "Results Dir"))
        self.label_4.setText(_translate("MainWindow", "Max Area"))
        self.label_2.setText(_translate("MainWindow", "Thresh_C"))
        self.label_3.setText(_translate("MainWindow", "Block Size"))
        self.pushButton_video.setText(_translate("MainWindow", "Video File"))
        self.pushButton_mask.setText(_translate("MainWindow", "Mask Dir"))
        self.label.setText(_translate("MainWindow", "Min Area"))
        self.pushButton_start.setText(_translate("MainWindow", "Start"))

