# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Mon Jul 27 16:33:14 2015
#      by: PyQt5 UI code generator 5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(859, 845)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_6 = QtWidgets.QLabel(self.centralWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.spinBox_min_area = QtWidgets.QSpinBox(self.centralWidget)
        self.spinBox_min_area.setMaximum(1000)
        self.spinBox_min_area.setObjectName("spinBox_min_area")
        self.gridLayout.addWidget(self.spinBox_min_area, 2, 0, 1, 1)
        self.spinBox_max_area = QtWidgets.QSpinBox(self.centralWidget)
        self.spinBox_max_area.setMinimum(500)
        self.spinBox_max_area.setMaximum(10000)
        self.spinBox_max_area.setObjectName("spinBox_max_area")
        self.gridLayout.addWidget(self.spinBox_max_area, 2, 1, 1, 1)
        self.dial_block_size = QtWidgets.QDial(self.centralWidget)
        self.dial_block_size.setMinimum(0)
        self.dial_block_size.setMaximum(200)
        self.dial_block_size.setObjectName("dial_block_size")
        self.gridLayout.addWidget(self.dial_block_size, 1, 2, 1, 1)
        self.spinBox_thresh_C = QtWidgets.QSpinBox(self.centralWidget)
        self.spinBox_thresh_C.setMinimum(-100)
        self.spinBox_thresh_C.setMaximum(100)
        self.spinBox_thresh_C.setObjectName("spinBox_thresh_C")
        self.gridLayout.addWidget(self.spinBox_thresh_C, 2, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 1)
        self.dial_max_area = QtWidgets.QDial(self.centralWidget)
        self.dial_max_area.setMinimum(500)
        self.dial_max_area.setMaximum(10000)
        self.dial_max_area.setObjectName("dial_max_area")
        self.gridLayout.addWidget(self.dial_max_area, 1, 1, 1, 1)
        self.dial_thresh_C = QtWidgets.QDial(self.centralWidget)
        self.dial_thresh_C.setMinimum(-100)
        self.dial_thresh_C.setMaximum(100)
        self.dial_thresh_C.setObjectName("dial_thresh_C")
        self.gridLayout.addWidget(self.dial_thresh_C, 1, 3, 1, 1)
        self.dial_min_area = QtWidgets.QDial(self.centralWidget)
        self.dial_min_area.setMaximum(1000)
        self.dial_min_area.setObjectName("dial_min_area")
        self.gridLayout.addWidget(self.dial_min_area, 1, 0, 1, 1)
        self.spinBox_block_size = QtWidgets.QSpinBox(self.centralWidget)
        self.spinBox_block_size.setMaximum(200)
        self.spinBox_block_size.setObjectName("spinBox_block_size")
        self.gridLayout.addWidget(self.spinBox_block_size, 2, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_video = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_video.setObjectName("pushButton_video")
        self.gridLayout_3.addWidget(self.pushButton_video, 0, 0, 1, 1)
        self.lineEdit_video = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_video.setObjectName("lineEdit_video")
        self.gridLayout_3.addWidget(self.lineEdit_video, 0, 1, 1, 1)
        self.pushButton_mask = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_mask.setObjectName("pushButton_mask")
        self.gridLayout_3.addWidget(self.pushButton_mask, 1, 0, 1, 1)
        self.lineEdit_mask = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_mask.setObjectName("lineEdit_mask")
        self.gridLayout_3.addWidget(self.lineEdit_mask, 1, 1, 1, 1)
        self.pushButton_results = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_results.setObjectName("pushButton_results")
        self.gridLayout_3.addWidget(self.pushButton_results, 2, 0, 1, 1)
        self.lineEdit_results = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_results.setObjectName("lineEdit_results")
        self.gridLayout_3.addWidget(self.lineEdit_results, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 859, 22))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_6.setText(_translate("MainWindow", "TextLabel"))
        self.label_5.setText(_translate("MainWindow", "TextLabel"))
        self.label_4.setText(_translate("MainWindow", "Max Area"))
        self.label_3.setText(_translate("MainWindow", "Block Size"))
        self.label_2.setText(_translate("MainWindow", "Thresh_C"))
        self.label.setText(_translate("MainWindow", "Min Area"))
        self.pushButton_video.setText(_translate("MainWindow", "Video File"))
        self.pushButton_mask.setText(_translate("MainWindow", "Mask Dir"))
        self.pushButton_results.setText(_translate("MainWindow", "Results Dir"))

